In [ ]:
import pandas as pd
import numpy as np

import numpy as np
import pandas as pd
import stat
import matplotlib.pyplot as plt
!pip install linearmodels

# Perform PooledOLS
from linearmodels import PooledOLS
import statsmodels.api as sm
from linearmodels import PanelOLS

!pip install linearmodels
from linearmodels import IV2SLS

import scipy

Requirement already satisfied: linearmodels in /usr/local/lib/python3.7/dist-packages (4.24)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.1.5)
Requirement already satisfied: patsy in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.5.1)
Requirement already satisfied: statsmodels>=0.11 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.12.2)
Requirement already satisfied: mypy-extensions>=0.4 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.4.3)
Requirement already satisfied: pyhdfe>=0.1 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.1.0)
Requirement already satisfied: property-cached>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.6.4)
Requirement already satisfied: scipy>=1.2 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.4.1)
Requirement already satisfied: Cython>=0.29.21 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.29.23)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->linearmodels) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->linearmodels) (1.15.0)
Requirement already satisfied: linearmodels in /usr/local/lib/python3.7/dist-packages (4.24)
Requirement already satisfied: statsmodels>=0.11 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.12.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.1.5)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.19.5)
Requirement already satisfied: pyhdfe>=0.1 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.1.0)
Requirement already satisfied: mypy-extensions>=0.4 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.4.3)
Requirement already satisfied: Cython>=0.29.21 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.29.23)
Requirement already satisfied: property-cached>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.6.4)
Requirement already satisfied: scipy>=1.2 in /usr/local/lib/python3.7/dist-packages (from linearmodels) (1.4.1)
Requirement already satisfied: patsy in /usr/local/lib/python3.7/dist-packages (from linearmodels) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->linearmodels) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24->linearmodels) (1.15.0)

In [ ]:
#Link to the Data. Upload the file to this code if necessary
#https://drive.google.com/drive/folders/19-K2__Kla8B5cg5j_-OZJ6shE58bcXvz

# 1. Data Analysis

In [ ]:
path ='/content/data6.xls'

In [ ]:
data = pd.read_excel(path)
data.head(5)

  ticker  year  meanagef  ...  NonFounderFamily     ln(Q)  ln(Asset)
0     AA  1992      95.0  ...                 0  0.211180   9.307748
1     AA  1993      95.0  ...                 0  0.202430   9.358493
2     AA  1994      95.0  ...                 0  0.268021   9.421670
3     AA  1995      95.0  ...                 0  0.308674   9.521011
4     AA  1996      95.0  ...                 0  0.398799   9.506727

[5 rows x 15 columns]

In [ ]:
data = data.dropna()

In [ ]:
pip install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)

In [ ]:
data.replace(np.nan, 0)

     ticker  year  meanagef  ...  NonFounderFamily     ln(Q)  ln(Asset)
0        AA  1992      95.0  ...                 0  0.211180   9.307748
1        AA  1993      95.0  ...                 0  0.202430   9.358493
2        AA  1994      95.0  ...                 0  0.268021   9.421670
3        AA  1995      95.0  ...                 0  0.308674   9.521011
4        AA  1996      95.0  ...                 0  0.398799   9.506727
...     ...   ...       ...  ...               ...       ...        ...
1461      Z  1995      95.0  ...                 0  0.073613   4.025352
1462      Z  1996      95.0  ...                 0  0.337870   4.025352
1463      Z  1997      95.0  ...                 0  0.420839   4.025352
1464      Z  1998      95.0  ...                 0 -0.134477   4.025352
1465      Z  1999      95.0  ...                 0 -0.133356   4.025352

[1459 rows x 15 columns]

# Table II Panel C

In [ ]:
t2b = data.drop(columns = ['year', 'digit2_in']).corr()
t2b = np.round(t2b, 3)

df = pd.DataFrame(t2b)
df.to_excel('table2b.xlsx')

In [ ]:
#t2b = data.drop(columns = ['year', 'digit2_in'])

table2b = pd.DataFrame(t2b)
table2b.to_excel(r'table2b.xlsx', index= True, header= True)
print(table2b)

                  meanagef  assets  ...  ln(Q)  ln(Asset)
meanagef             1.000   0.088  ... -0.167     -0.284
assets               0.088   1.000  ... -0.091     -0.004
bs_volatility       -0.368  -0.090  ... -0.139      0.237
roa                 -0.147  -0.078  ...  0.685     -0.113
founderCEO          -0.728  -0.075  ...  0.149      0.109
Q                   -0.180  -0.055  ...  0.933     -0.085
hightech            -0.165  -0.032  ...  0.050      0.148
Location             0.014  -0.045  ... -0.025     -0.104
FamFirm             -0.308  -0.060  ...  0.118     -0.037
NonFounderFamily     0.072  -0.023  ...  0.036     -0.080
ln(Q)               -0.167  -0.091  ...  1.000     -0.108
ln(Asset)           -0.284  -0.004  ... -0.108      1.000

[12 rows x 12 columns]

# Table II Panel B

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['meanagef'],
                data[data['FamFirm'] == 0]['meanagef']))

Ttest_indResult(statistic=-12.335706491737094, pvalue=2.5137094744352826e-33)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['assets'],
                data[data['FamFirm'] == 0]['assets']))

Ttest_indResult(statistic=-2.2752414522954525, pvalue=0.02303615848140187)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['bs_volatility'],
                data[data['FamFirm'] == 0]['bs_volatility']))

Ttest_indResult(statistic=1.85376828752283, pvalue=0.06397431562543653)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['roa'],
                data[data['FamFirm'] == 0]['roa']))

Ttest_indResult(statistic=4.650898990857291, pvalue=3.6043869589410782e-06)

In [ ]:

print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['Q'],
                data[data['FamFirm'] == 0]['Q']))

Ttest_indResult(statistic=3.413536367631219, pvalue=0.0006588432779250759)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['ln(Q)'],
                data[data['FamFirm'] == 0]['ln(Q)']))

Ttest_indResult(statistic=4.530450409428892, pvalue=6.36636368806852e-06)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['ln(Asset)'],
                data[data['FamFirm'] == 0]['ln(Asset)']))

Ttest_indResult(statistic=-1.4000605466348142, pvalue=0.16170808387181806)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['founderCEO'],
                data[data['FamFirm'] == 0]['founderCEO']))

Ttest_indResult(statistic=13.762343901290086, pvalue=1.3222727393383731e-40)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['NonFounderFamily'],
                data[data['FamFirm'] == 0]['NonFounderFamily']))

Ttest_indResult(statistic=63.02286249581979, pvalue=0.0)

In [ ]:
print(scipy.stats.ttest_ind(data[data['FamFirm'] == 1]['hightech'],
                data[data['FamFirm'] == 0]['hightech']))

Ttest_indResult(statistic=-2.309878754623473, pvalue=0.021034067517491543)

In [ ]:
mean= data.groupby(data['ticker'])['assets'].mean()
print(mean)

ticker
AA      13708.200073
AAPL     4996.981384
ABS      6131.519392
ABT     10430.003540
ADM     10038.071498
            ...
WY      14362.606323
XOM     97134.375000
XRX     31342.875000
YELL     1276.808437
Z        3626.625000
Name: assets, Length: 193, dtype: float64

# Table II panel A

In [ ]:
table2 = data.describe()
table2.to_excel(r'table2.xlsx', index= True, header= True)
print(table2)

              year     meanagef  ...        ln(Q)    ln(Asset)
count  1459.000000  1459.000000  ...  1459.000000  1459.000000
mean   1995.601782    90.395533  ...     0.597114     3.639374
std       2.212577    11.752475  ...     0.441802     0.686623
min    1992.000000    39.000000  ...    -0.173796     2.564949
25%    1994.000000    95.000000  ...     0.275070     3.332205
50%    1996.000000    95.000000  ...     0.491456     3.583519
75%    1997.000000    95.000000  ...     0.838553     3.912023
max    1999.000000    95.000000  ...     2.779245     9.767811

[8 rows x 14 columns]

# Table I

In [ ]:
#col1 = data.groupby(data['digit2_in'])['founderCEO'].count()
#col1
Number_of_founder_CEO= data.groupby(data['digit2_in'])['founderCEO'].sum()
Number_of_founder_CEO
#Percent_Family_Firms_in_Industry = total1/col1*100

#data['family_firm'] = total1
#data['Percent_Family_Firms_in_Industry'] = Percent_Family_Firms_in_Industry

digit2_in
13     0
16     0
20     0
21     0
23     0
24     0
25     0
26     3
27     0
28     0
29     3
30    16
32     0
33     0
34     0
35    10
36     6
37     5
38     0
39     0
40     0
42     0
45     8
48     7
49     0
50     0
51     0
52     8
53     5
54     0
56    11
57     0
58     0
59     4
63     4
70     0
73    16
75     0
78     0
80     0
Name: founderCEO, dtype: int64

In [ ]:
#col2 = data.groupby(data['digit2_in'])['NonFounderFamily'].count()
Number_of_Non_founder_CEO =data.groupby(data['digit2_in'])['NonFounderFamily'].sum()
Number_of_Non_founder_CEO
#Percent_Non_Family_Firms_in_Industry = total2/col2*100
#Percent_Non_Family_Firms_in_Industry

#data['non_family_firm'] = total2
#data['Percent_Non_Family_Firms_in_Industry'] = Percent_Non_Family_Firms_in_Industry

digit2_in
13     0
16     0
20    45
21     0
23     8
24    15
25     0
26    15
27    47
28    32
29    12
30     8
32     0
33    16
34    15
35    30
36    16
37    33
38     0
39     8
40     0
42     7
45     0
48     7
49     0
50     8
51     8
52     0
53     9
54    18
56    19
57     0
58     0
59    26
63     2
70    14
73     0
75     0
78     0
80     0
Name: NonFounderFamily, dtype: int64

In [ ]:
Total = Number_of_founder_CEO + Number_of_Non_founder_CEO 
Total
Percentage_of_founder_CEO = Number_of_founder_CEO/ Total* 100
Percentage_of_Non_founder_CEO = 100- Percentage_of_founder_CEO

In [ ]:
Percentage_of_founder_CEO

digit2_in
13           NaN
16           NaN
20      0.000000
21           NaN
23      0.000000
24      0.000000
25           NaN
26     16.666667
27      0.000000
28      0.000000
29     20.000000
30     66.666667
32           NaN
33      0.000000
34      0.000000
35     25.000000
36     27.272727
37     13.157895
38           NaN
39      0.000000
40           NaN
42      0.000000
45    100.000000
48     50.000000
49           NaN
50      0.000000
51      0.000000
52    100.000000
53     35.714286
54      0.000000
56     36.666667
57           NaN
58           NaN
59     13.333333
63     66.666667
70      0.000000
73    100.000000
75           NaN
78           NaN
80           NaN
dtype: float64

In [ ]:
Percentage_of_Non_founder_CEO

digit2_in
13           NaN
16           NaN
20    100.000000
21           NaN
23    100.000000
24    100.000000
25           NaN
26     83.333333
27    100.000000
28    100.000000
29     80.000000
30     33.333333
32           NaN
33    100.000000
34    100.000000
35     75.000000
36     72.727273
37     86.842105
38           NaN
39    100.000000
40           NaN
42    100.000000
45      0.000000
48     50.000000
49           NaN
50    100.000000
51    100.000000
52      0.000000
53     64.285714
54    100.000000
56     63.333333
57           NaN
58           NaN
59     86.666667
63     33.333333
70    100.000000
73      0.000000
75           NaN
78           NaN
80           NaN
dtype: float64

In [ ]:
pip install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)

In [ ]:
from tabulate import tabulate

In [ ]:
result = [Number_of_founder_CEO, Number_of_Non_founder_CEO, Percentage_of_founder_CEO]
result

[digit2_in
 13     0
 16     0
 20     0
 21     0
 23     0
 24     0
 25     0
 26     3
 27     0
 28     0
 29     3
 30    16
 32     0
 33     0
 34     0
 35    10
 36     6
 37     5
 38     0
 39     0
 40     0
 42     0
 45     8
 48     7
 49     0
 50     0
 51     0
 52     8
 53     5
 54     0
 56    11
 57     0
 58     0
 59     4
 63     4
 70     0
 73    16
 75     0
 78     0
 80     0
 Name: founderCEO, dtype: int64, digit2_in
 13     0
 16     0
 20    45
 21     0
 23     8
 24    15
 25     0
 26    15
 27    47
 28    32
 29    12
 30     8
 32     0
 33    16
 34    15
 35    30
 36    16
 37    33
 38     0
 39     8
 40     0
 42     7
 45     0
 48     7
 49     0
 50     8
 51     8
 52     0
 53     9
 54    18
 56    19
 57     0
 58     0
 59    26
 63     2
 70    14
 73     0
 75     0
 78     0
 80     0
 Name: NonFounderFamily, dtype: int64, digit2_in
 13           NaN
 16           NaN
 20      0.000000
 21           NaN
 23      0.000000
 24      0.000000
 25           NaN
 26     16.666667
 27      0.000000
 28      0.000000
 29     20.000000
 30     66.666667
 32           NaN
 33      0.000000
 34      0.000000
 35     25.000000
 36     27.272727
 37     13.157895
 38           NaN
 39      0.000000
 40           NaN
 42      0.000000
 45    100.000000
 48     50.000000
 49           NaN
 50      0.000000
 51      0.000000
 52    100.000000
 53     35.714286
 54      0.000000
 56     36.666667
 57           NaN
 58           NaN
 59     13.333333
 63     66.666667
 70      0.000000
 73    100.000000
 75           NaN
 78           NaN
 80           NaN
 dtype: float64]

In [ ]:
Percentage_of_Non_founder_CEO = 100- Percentage_of_founder_CEO
Percentage_of_Non_founder_CEO

digit2_in
13           NaN
16           NaN
20    100.000000
21           NaN
23    100.000000
24    100.000000
25           NaN
26     83.333333
27    100.000000
28    100.000000
29     80.000000
30     33.333333
32           NaN
33    100.000000
34    100.000000
35     75.000000
36     72.727273
37     86.842105
38           NaN
39    100.000000
40           NaN
42    100.000000
45      0.000000
48     50.000000
49           NaN
50    100.000000
51    100.000000
52      0.000000
53     64.285714
54    100.000000
56     63.333333
57           NaN
58           NaN
59     86.666667
63     33.333333
70    100.000000
73      0.000000
75           NaN
78           NaN
80           NaN
dtype: float64

In [ ]:
df = pd.DataFrame(result)

In [ ]:
df.to_excel(r'table1.xlsx', index= False, header= True)

In [ ]:
data.head(20)

   ticker  year  meanagef  ...  NonFounderFamily     ln(Q)  ln(Asset)
0      AA  1992      95.0  ...                 0  0.211180   9.307748
1      AA  1993      95.0  ...                 0  0.202430   9.358493
2      AA  1994      95.0  ...                 0  0.268021   9.421670
3      AA  1995      95.0  ...                 0  0.308674   9.521011
4      AA  1996      95.0  ...                 0  0.398799   9.506727
5      AA  1997      95.0  ...                 0  0.452467   9.478121
6      AA  1998      95.0  ...                 0  0.364802   9.767811
7      AA  1999      95.0  ...                 0  0.881733   9.744843
8    AAPL  1992      42.0  ...                 0  0.558428   8.348465
9    AAPL  1993      42.0  ...                 0  0.124999   8.550901
10   AAPL  1994      42.0  ...                 0  0.270012   8.575980
11   AAPL  1995      42.0  ...                 0  0.238445   8.737292
12   AAPL  1996      42.0  ...                 0  0.123354   8.587465
13   AAPL  1997      42.0  ...                 0  0.341795   8.350666
14   AAPL  1998      42.0  ...                 0  0.614614   8.363809
15   AAPL  1999      42.0  ...                 0  0.875978   8.548886
16    ABS  1993      87.0  ...                 1  0.969126   8.100130
17    ABS  1994      87.0  ...                 1  0.966612   3.988984
18    ABS  1995      87.0  ...                 1  0.952137   3.988984
19    ABS  1996      87.0  ...                 1  0.868965   3.988984

[20 rows x 15 columns]

In [ ]:
data.head()

  ticker  year  meanagef  ...  NonFounderFamily     ln(Q)  ln(Asset)
0     AA  1992      95.0  ...                 0  0.211180   9.307748
1     AA  1993      95.0  ...                 0  0.202430   9.358493
2     AA  1994      95.0  ...                 0  0.268021   9.421670
3     AA  1995      95.0  ...                 0  0.308674   9.521011
4     AA  1996      95.0  ...                 0  0.398799   9.506727

[5 rows x 15 columns]

#4.  Multivariate Analysis

In [ ]:
pd.get_dummies(data['year'])

      1992  1993  1994  1995  1996  1997  1998  1999
0        1     0     0     0     0     0     0     0
1        0     1     0     0     0     0     0     0
2        0     0     1     0     0     0     0     0
3        0     0     0     1     0     0     0     0
4        0     0     0     0     1     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...
1461     0     0     0     1     0     0     0     0
1462     0     0     0     0     1     0     0     0
1463     0     0     0     0     0     1     0     0
1464     0     0     0     0     0     0     1     0
1465     0     0     0     0     0     0     0     1

[1459 rows x 8 columns]

In [ ]:
 pd.get_dummies(data['digit2_in'])

      13  16  20  21  23  24  25  26  27  ...  57  58  59  63  70  73  75  78  80
0      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
3      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
4      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
1461   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1462   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1463   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1464   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1465   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0

[1459 rows x 40 columns]

In [ ]:
#Create Dummy Variable
#type(data[['FamFirm']])

X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))
X.head()

   FamFirm  bs_volatility  ln(Asset)  hightech  1992  ...  70  73  75  78  80
0        0          0.246   9.307748         0     1  ...   0   0   0   0   0
1        0          0.228   9.358493         0     0  ...   0   0   0   0   0
2        0          0.222   9.421670         0     0  ...   0   0   0   0   0
3        0          0.213   9.521011         0     0  ...   0   0   0   0   0
4        0          0.206   9.506727         0     0  ...   0   0   0   0   0

[5 rows x 52 columns]

In [ ]:
np.asarray(data)

array([['AA', 1992, 95.0, ..., 0, 0.21117985676997297, 9.307748314425707],
       ['AA', 1993, 95.0, ..., 0, 0.20242973859839372, 9.358493133683375],
       ['AA', 1994, 95.0, ..., 0, 0.2680212750783413, 9.421670433615525],
       ...,
       ['Z', 1997, 95.0, ..., 0, 0.42083892131216216, 4.02535169073515],
       ['Z', 1998, 95.0, ..., 0, -0.13447720348857214, 4.02535169073515],
       ['Z', 1999, 95.0, ..., 0, -0.13335552329865624, 4.02535169073515]],
      dtype=object)

In [ ]:
#Mutlivariate Analysis

In [ ]:
print(data['Q'])

0       1.235134
1       1.224374
2       1.307375
3       1.361618
4       1.490034
          ...
1461    1.076390
1462    1.401959
1463    1.523239
1464    0.874173
1465    0.875154
Name: Q, Length: 1459, dtype: float64

In [ ]:
print(X)

      FamFirm  bs_volatility  ln(Asset)  hightech  1992  ...  70  73  75  78  80
0           0          0.246   9.307748         0     1  ...   0   0   0   0   0
1           0          0.228   9.358493         0     0  ...   0   0   0   0   0
2           0          0.222   9.421670         0     0  ...   0   0   0   0   0
3           0          0.213   9.521011         0     0  ...   0   0   0   0   0
4           0          0.206   9.506727         0     0  ...   0   0   0   0   0
...       ...            ...        ...       ...   ...  ...  ..  ..  ..  ..  ..
1461        0          0.315   4.025352         0     0  ...   0   0   0   0   0
1462        0          0.365   4.025352         0     0  ...   0   0   0   0   0
1463        0          0.396   4.025352         0     0  ...   0   0   0   0   0
1464        0          0.466   4.025352         0     0  ...   0   0   0   0   0
1465        0          0.530   4.025352         0     0  ...   0   0   0   0   0

[1459 rows x 52 columns]

In [ ]:
np.asarray(X).dtype

dtype('float64')

In [ ]:
#Column I

y = data['Q']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X.astype(float))
results = model.fit()


#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.28845515204545724
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.288
Model:                            OLS   Adj. R-squared:                  0.264
Method:                 Least Squares   F-statistic:                     11.66
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.68e-73
Time:                        11:04:52   Log-Likelihood:                -2150.2
No. Observations:                1459   AIC:                             4400.
Df Residuals:                    1409   BIC:                             4665.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.7061      0.193      8.847      0.000       1.328       2.084
FamFirm           0.2455      0.068      3.593      0.000       0.111       0.379
bs_volatility    -0.5581      0.410     -1.362      0.173      -1.362       0.245
ln(Asset)        -0.0222      0.052     -0.430      0.668      -0.124       0.079
hightech          0.3742      0.070      5.378      0.000       0.238       0.511
1992              0.0119      0.090      0.132      0.895      -0.164       0.188
1993             -0.0218      0.078     -0.280      0.779      -0.175       0.131
1994             -0.0997      0.077     -1.293      0.196      -0.251       0.052
1995              0.0380      0.076      0.501      0.617      -0.111       0.187
1996              0.1475      0.076      1.948      0.052      -0.001       0.296
1997              0.4434      0.076      5.854      0.000       0.295       0.592
1998              0.6184      0.079      7.862      0.000       0.464       0.773
1999              0.5684      0.082      6.896      0.000       0.407       0.730
13               -0.1305      0.231     -0.566      0.572      -0.583       0.322
16               -0.2033      0.279     -0.729      0.466      -0.750       0.344
20                1.1245      0.120      9.344      0.000       0.888       1.361
21                0.4583      0.374      1.224      0.221      -0.276       1.193
23               -0.3123      0.376     -0.831      0.406      -1.049       0.425
24               -0.2931      0.278     -1.055      0.292      -0.838       0.252
25               -0.4218      0.374     -1.127      0.260      -1.156       0.312
26                0.0251      0.151      0.167      0.868      -0.270       0.320
27                0.0466      0.143      0.326      0.745      -0.234       0.327
28                1.3605      0.097     14.037      0.000       1.170       1.551
29               -0.3188      0.153     -2.078      0.038      -0.620      -0.018
30                0.1317      0.193      0.683      0.495      -0.247       0.510
32               -0.0494      0.400     -0.124      0.902      -0.835       0.736
33               -0.0561      0.165     -0.339      0.734      -0.381       0.268
34                0.1835      0.174      1.057      0.291      -0.157       0.524
35               -0.2611      0.101     -2.590      0.010      -0.459      -0.063
36               -0.0262      0.114     -0.229      0.819      -0.251       0.198
37               -0.3465      0.105     -3.291      0.001      -0.553      -0.140
38               -0.2683      0.166     -1.616      0.106      -0.594       0.057
39                0.1461      0.228      0.642      0.521      -0.301       0.593
40               -0.3457      0.198     -1.747      0.081      -0.734       0.042
42               -0.8382      0.401     -2.090      0.037      -1.625      -0.051
45               -0.4488      0.169     -2.650      0.008      -0.781      -0.117
48                0.1540      0.200      0.771      0.441      -0.238       0.546
49               -0.4465      0.374     -1.195      0.232      -1.179       0.286
50                0.0795      0.197      0.405      0.686      -0.306       0.465
51               -0.2913      0.165     -1.766      0.078      -0.615       0.032
52                1.4015      0.228      6.150      0.000       0.954       1.849
53               -0.2358      0.153     -1.545      0.123      -0.535       0.064
54                0.3127      0.218      1.436      0.151      -0.114       0.740
56                0.5967      0.182      3.279      0.001       0.240       0.954
57                0.3610      0.278      1.300      0.194      -0.184       0.906
58                0.7825      0.400      1.956      0.051      -0.002       1.567
59                0.1000      0.184      0.542      0.588      -0.262       0.462
63               -0.3084      0.437     -0.706      0.481      -1.166       0.549
70               -0.2070      0.289     -0.717      0.474      -0.774       0.360
73                0.9299      0.142      6.532      0.000       0.651       1.209
75               -0.5299      0.375     -1.413      0.158      -1.265       0.206
78                0.1685      0.375      0.450      0.653      -0.567       0.904
80               -0.3176      0.402     -0.791      0.429      -1.105       0.470
==============================================================================
Omnibus:                     1070.535   Durbin-Watson:                   0.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            31453.916
Skew:                           3.075   Prob(JB):                         0.00
Kurtosis:                      24.900   Cond. No.                     3.23e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.11e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column II


y = data['Q']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit(cov_type='HC3')


#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.28845515204545724
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.288
Model:                            OLS   Adj. R-squared:                  0.264
Method:                 Least Squares   F-statistic:                     295.3
Date:                Wed, 04 Aug 2021   Prob (F-statistic):               0.00
Time:                        10:37:58   Log-Likelihood:                -2150.2
No. Observations:                1459   AIC:                             4400.
Df Residuals:                    1409   BIC:                             4665.
Df Model:                          49
Covariance Type:                  HC3
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.7061      0.131     13.056      0.000       1.450       1.962
FamFirm           0.2455      0.079      3.101      0.002       0.090       0.401
bs_volatility    -0.5581      0.441     -1.265      0.206      -1.423       0.307
ln(Asset)        -0.0222      0.022     -0.998      0.318      -0.066       0.021
hightech          0.3742      0.079      4.710      0.000       0.219       0.530
1992              0.0119      0.074      0.161      0.872      -0.133       0.157
1993             -0.0218      0.057     -0.383      0.702      -0.133       0.090
1994             -0.0997      0.055     -1.806      0.071      -0.208       0.009
1995              0.0380      0.059      0.650      0.516      -0.077       0.153
1996              0.1475      0.063      2.344      0.019       0.024       0.271
1997              0.4434      0.076      5.804      0.000       0.294       0.593
1998              0.6184      0.102      6.054      0.000       0.418       0.819
1999              0.5684      0.107      5.308      0.000       0.359       0.778
13               -0.1305      0.104     -1.255      0.210      -0.334       0.073
16               -0.2033      0.167     -1.219      0.223      -0.530       0.124
20                1.1245      0.152      7.419      0.000       0.827       1.422
21                0.4583      0.155      2.961      0.003       0.155       0.762
23               -0.3123      0.124     -2.514      0.012      -0.556      -0.069
24               -0.2931      0.116     -2.523      0.012      -0.521      -0.065
25               -0.4218      0.106     -3.983      0.000      -0.629      -0.214
26                0.0251      0.107      0.234      0.815      -0.185       0.235
27                0.0466      0.078      0.596      0.551      -0.107       0.200
28                1.3605      0.146      9.301      0.000       1.074       1.647
29               -0.3188      0.068     -4.701      0.000      -0.452      -0.186
30                0.1317      0.140      0.939      0.348      -0.143       0.407
32               -0.0494      0.209     -0.236      0.813      -0.460       0.361
33               -0.0561      0.135     -0.415      0.678      -0.321       0.209
34                0.1835      0.217      0.847      0.397      -0.241       0.608
35               -0.2611      0.101     -2.578      0.010      -0.460      -0.063
36               -0.0262      0.119     -0.219      0.827      -0.260       0.208
37               -0.3465      0.043     -8.061      0.000      -0.431      -0.262
38               -0.2683      0.093     -2.898      0.004      -0.450      -0.087
39                0.1461      0.165      0.888      0.375      -0.177       0.469
40               -0.3457      0.079     -4.382      0.000      -0.500      -0.191
42               -0.8382      0.138     -6.054      0.000      -1.109      -0.567
45               -0.4488      0.057     -7.889      0.000      -0.560      -0.337
48                0.1540      0.080      1.916      0.055      -0.004       0.311
49               -0.4465      0.076     -5.911      0.000      -0.595      -0.298
50                0.0795      0.129      0.619      0.536      -0.172       0.331
51               -0.2913      0.087     -3.354      0.001      -0.461      -0.121
52                1.4015      0.349      4.016      0.000       0.718       2.086
53               -0.2358      0.093     -2.533      0.011      -0.418      -0.053
54                0.3127      0.128      2.444      0.015       0.062       0.563
56                0.5967      0.279      2.142      0.032       0.051       1.143
57                0.3610      0.220      1.640      0.101      -0.070       0.792
58                0.7825      0.119      6.602      0.000       0.550       1.015
59                0.1000      0.140      0.715      0.475      -0.174       0.374
63               -0.3084      0.354     -0.871      0.384      -1.002       0.385
70               -0.2070      0.125     -1.658      0.097      -0.452       0.038
73                0.9299      0.277      3.363      0.001       0.388       1.472
75               -0.5299      0.125     -4.233      0.000      -0.775      -0.285
78                0.1685      0.161      1.050      0.294      -0.146       0.483
80               -0.3176      0.135     -2.357      0.018      -0.582      -0.053
==============================================================================
Omnibus:                     1070.535   Durbin-Watson:                   0.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            31453.916
Skew:                           3.075   Prob(JB):                         0.00
Kurtosis:                      24.900   Cond. No.                     3.23e+16
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The smallest eigenvalue is 2.11e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/lib/python3.7/dist-packages/statsmodels/base/model.py:1834: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 52, but rank is 50
  'rank is %d' % (J, J_), ValueWarning)

In [ ]:
#Column III
y = data['Q']
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.290
Method:                 Least Squares   F-statistic:                     13.14
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.18e-83
Time:                        10:37:59   Log-Likelihood:                -2124.0
No. Observations:                1459   AIC:                             4348.
Df Residuals:                    1409   BIC:                             4612.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.9234      0.187     10.274      0.000       1.556       2.291
founderCEO        0.9827      0.122      8.061      0.000       0.744       1.222
bs_volatility    -1.0657      0.408     -2.611      0.009      -1.866      -0.265
ln(Asset)        -0.0476      0.051     -0.942      0.347      -0.147       0.052
hightech          0.3263      0.068      4.783      0.000       0.192       0.460
1992              0.0266      0.088      0.302      0.763      -0.146       0.199
1993             -0.0089      0.076     -0.116      0.907      -0.159       0.141
1994             -0.0830      0.076     -1.098      0.273      -0.231       0.065
1995              0.0535      0.074      0.719      0.472      -0.092       0.200
1996              0.1662      0.074      2.238      0.025       0.021       0.312
1997              0.4650      0.074      6.261      0.000       0.319       0.611
1998              0.6713      0.077      8.686      0.000       0.520       0.823
1999              0.6327      0.081      7.795      0.000       0.473       0.792
13               -0.1785      0.225     -0.794      0.428      -0.620       0.263
16               -0.2243      0.273     -0.823      0.411      -0.759       0.310
20                1.1742      0.118      9.938      0.000       0.942       1.406
21                0.4230      0.367      1.153      0.249      -0.297       1.143
23               -0.1108      0.367     -0.302      0.763      -0.830       0.609
24               -0.0851      0.270     -0.316      0.752      -0.614       0.444
25               -0.4683      0.367     -1.277      0.202      -1.187       0.251
26               -0.0035      0.148     -0.024      0.981      -0.293       0.286
27                0.1843      0.138      1.333      0.183      -0.087       0.455
28                1.3684      0.095     14.438      0.000       1.183       1.554
29               -0.3712      0.151     -2.463      0.014      -0.667      -0.076
30               -0.1732      0.194     -0.892      0.373      -0.554       0.208
32               -0.0293      0.392     -0.075      0.941      -0.799       0.741
33                0.0400      0.163      0.246      0.806      -0.279       0.359
34                0.2426      0.171      1.422      0.155      -0.092       0.577
35               -0.2081      0.099     -2.103      0.036      -0.402      -0.014
36               -0.0013      0.112     -0.011      0.991      -0.222       0.219
37               -0.3245      0.103     -3.137      0.002      -0.527      -0.122
38               -0.2504      0.162     -1.542      0.123      -0.569       0.068
39                0.2399      0.224      1.071      0.284      -0.199       0.679
40               -0.3751      0.193     -1.943      0.052      -0.754       0.004
42               -0.5747      0.392     -1.467      0.143      -1.343       0.194
45               -0.5558      0.166     -3.347      0.001      -0.882      -0.230
48                0.0289      0.197      0.147      0.883      -0.357       0.415
49               -0.4705      0.366     -1.284      0.199      -1.189       0.248
50                0.1347      0.193      0.697      0.486      -0.244       0.514
51               -0.2445      0.162     -1.509      0.132      -0.562       0.073
52                1.1276      0.227      4.977      0.000       0.683       1.572
53               -0.2684      0.150     -1.791      0.074      -0.562       0.026
54                0.4778      0.212      2.251      0.025       0.061       0.894
56                0.5427      0.177      3.059      0.002       0.195       0.891
57                0.4003      0.272      1.471      0.142      -0.134       0.934
58                0.7442      0.392      1.897      0.058      -0.026       1.514
59                0.1652      0.179      0.925      0.355      -0.185       0.515
63               -0.6458      0.432     -1.497      0.135      -1.492       0.201
70                0.0509      0.280      0.182      0.856      -0.499       0.600
73                0.7861      0.141      5.568      0.000       0.509       1.063
75               -0.5419      0.368     -1.473      0.141      -1.263       0.180
78                0.1723      0.368      0.469      0.639      -0.549       0.894
80               -0.2745      0.394     -0.697      0.486      -1.048       0.499
==============================================================================
Omnibus:                     1057.289   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            29838.921
Skew:                           3.032   Prob(JB):                         0.00
Kurtosis:                      24.309   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column IV
y = data['Q']
X=data[['NonFounderFamily','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.2822695955375779
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.282
Model:                            OLS   Adj. R-squared:                  0.257
Method:                 Least Squares   F-statistic:                     11.31
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           4.51e-71
Time:                        10:37:59   Log-Likelihood:                -2156.6
No. Observations:                1459   AIC:                             4413.
Df Residuals:                    1409   BIC:                             4677.
Df Model:                          49
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                1.8507      0.194      9.516      0.000       1.469       2.232
NonFounderFamily    -0.0595      0.073     -0.811      0.417      -0.203       0.084
bs_volatility       -0.5049      0.411     -1.227      0.220      -1.312       0.302
ln(Asset)           -0.0425      0.052     -0.820      0.412      -0.144       0.059
hightech             0.3481      0.070      4.963      0.000       0.211       0.486
1992                 0.0251      0.090      0.278      0.781      -0.152       0.202
1993                -0.0039      0.078     -0.050      0.960      -0.157       0.149
1994                -0.0820      0.077     -1.059      0.290      -0.234       0.070
1995                 0.0570      0.076      0.748      0.454      -0.092       0.207
1996                 0.1676      0.076      2.203      0.028       0.018       0.317
1997                 0.4631      0.076      6.089      0.000       0.314       0.612
1998                 0.6383      0.079      8.064      0.000       0.483       0.794
1999                 0.5855      0.083      7.056      0.000       0.423       0.748
13                  -0.2547      0.231     -1.101      0.271      -0.708       0.199
16                  -0.3261      0.280     -1.166      0.244      -0.875       0.222
20                   1.1502      0.121      9.500      0.000       0.913       1.388
21                   0.3436      0.376      0.914      0.361      -0.394       1.081
23                  -0.1190      0.378     -0.315      0.753      -0.861       0.623
24                  -0.0999      0.280     -0.357      0.721      -0.650       0.450
25                  -0.5312      0.376     -1.414      0.157      -1.268       0.206
26                   0.0006      0.151      0.004      0.997      -0.296       0.297
27                   0.1662      0.145      1.148      0.251      -0.118       0.450
28                   1.3153      0.097     13.553      0.000       1.125       1.506
29                  -0.3415      0.154     -2.215      0.027      -0.644      -0.039
30                   0.2203      0.192      1.147      0.252      -0.157       0.597
32                  -0.1611      0.402     -0.401      0.688      -0.949       0.627
33                  -0.0382      0.166     -0.230      0.819      -0.364       0.288
34                   0.1970      0.174      1.129      0.259      -0.145       0.539
35                  -0.2316      0.102     -2.280      0.023      -0.431      -0.032
36                  -0.0198      0.115     -0.172      0.863      -0.245       0.206
37                  -0.3557      0.106     -3.364      0.001      -0.563      -0.148
38                  -0.3439      0.166     -2.068      0.039      -0.670      -0.018
39                   0.1524      0.229      0.666      0.506      -0.296       0.601
40                  -0.4458      0.198     -2.247      0.025      -0.835      -0.057
42                  -0.6384      0.404     -1.580      0.114      -1.431       0.154
45                  -0.5075      0.171     -2.974      0.003      -0.842      -0.173
48                   0.1878      0.200      0.937      0.349      -0.205       0.581
49                  -0.5428      0.375     -1.447      0.148      -1.279       0.193
50                   0.0635      0.197      0.322      0.748      -0.324       0.451
51                  -0.3345      0.165     -2.022      0.043      -0.659      -0.010
52                   1.3938      0.230      6.068      0.000       0.943       1.844
53                  -0.2565      0.153     -1.672      0.095      -0.557       0.044
54                   0.4401      0.219      2.005      0.045       0.010       0.871
56                   0.7203      0.181      3.974      0.000       0.365       1.076
57                   0.2611      0.278      0.938      0.349      -0.285       0.807
58                   0.6907      0.402      1.719      0.086      -0.097       1.479
59                   0.2408      0.186      1.298      0.194      -0.123       0.605
63                  -0.1451      0.437     -0.332      0.740      -1.002       0.712
70                   0.0054      0.292      0.018      0.985      -0.567       0.577
73                   0.9435      0.143      6.595      0.000       0.663       1.224
75                  -0.6177      0.377     -1.641      0.101      -1.356       0.121
78                   0.0800      0.376      0.212      0.832      -0.658       0.818
80                  -0.4106      0.403     -1.019      0.309      -1.201       0.380
==============================================================================
Omnibus:                     1078.554   Durbin-Watson:                   0.653
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            32244.551
Skew:                           3.103   Prob(JB):                         0.00
Kurtosis:                      25.179   Cond. No.                     3.91e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.43e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column V

y = data['roa']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.23051635480021704
                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.231
Model:                            OLS   Adj. R-squared:                  0.204
Method:                 Least Squares   F-statistic:                     8.614
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           7.98e-52
Time:                        10:37:59   Log-Likelihood:                -4359.9
No. Observations:                1459   AIC:                             8820.
Df Residuals:                    1409   BIC:                             9084.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             7.3944      0.877      8.433      0.000       5.674       9.115
FamFirm           1.2584      0.311      4.051      0.000       0.649       1.868
bs_volatility   -10.9785      1.863     -5.894      0.000     -14.632      -7.324
ln(Asset)        -0.2483      0.235     -1.057      0.291      -0.709       0.213
hightech          1.6024      0.316      5.065      0.000       0.982       2.223
1992              0.5522      0.408      1.353      0.176      -0.249       1.353
1993              0.1311      0.354      0.371      0.711      -0.563       0.825
1994              1.1331      0.351      3.231      0.001       0.445       1.821
1995              0.9736      0.345      2.821      0.005       0.297       1.651
1996              0.8313      0.344      2.413      0.016       0.156       1.507
1997              0.8476      0.344      2.461      0.014       0.172       1.523
1998              1.0632      0.358      2.973      0.003       0.362       1.765
1999              1.8623      0.375      4.968      0.000       1.127       2.598
13               -2.2967      1.049     -2.190      0.029      -4.354      -0.239
16               -1.1781      1.268     -0.929      0.353      -3.666       1.310
20                3.1819      0.547      5.814      0.000       2.108       4.255
21                5.3195      1.703      3.124      0.002       1.979       8.660
23                2.2533      1.709      1.319      0.187      -1.099       5.605
24               -0.8448      1.263     -0.669      0.504      -3.323       1.633
25               -0.9107      1.701     -0.535      0.592      -4.248       2.426
26               -0.4909      0.685     -0.717      0.473      -1.834       0.852
27                0.0836      0.651      0.129      0.898      -1.192       1.360
28                4.9276      0.441     11.180      0.000       4.063       5.792
29               -1.9629      0.698     -2.814      0.005      -3.331      -0.594
30                3.2564      0.877      3.712      0.000       1.535       4.977
32               -3.9495      1.820     -2.170      0.030      -7.520      -0.380
33               -0.3909      0.752     -0.520      0.603      -1.867       1.085
34               -0.4462      0.790     -0.565      0.572      -1.995       1.103
35               -0.4399      0.459     -0.959      0.338      -1.339       0.460
36                0.7149      0.521      1.373      0.170      -0.306       1.736
37               -0.3758      0.479     -0.785      0.433      -1.315       0.563
38               -0.4546      0.755     -0.602      0.547      -1.936       1.027
39                2.0502      1.035      1.980      0.048       0.019       4.081
40               -0.9755      0.900     -1.084      0.278      -2.740       0.789
42               -3.8284      1.824     -2.099      0.036      -7.406      -0.251
45               -1.0551      0.770     -1.370      0.171      -2.566       0.455
48               -0.1357      0.908     -0.149      0.881      -1.918       1.646
49               -2.3419      1.699     -1.379      0.168      -5.674       0.990
50                1.8566      0.894      2.077      0.038       0.103       3.610
51               -1.7803      0.750     -2.373      0.018      -3.252      -0.309
52                3.8387      1.036      3.704      0.000       1.806       5.872
53               -0.2713      0.694     -0.391      0.696      -1.633       1.090
54                1.6281      0.990      1.644      0.100      -0.314       3.570
56                5.2420      0.828      6.335      0.000       3.619       6.865
57                2.5977      1.263      2.057      0.040       0.121       5.075
58                3.6374      1.819      2.000      0.046       0.069       7.205
59               -0.5207      0.839     -0.621      0.535      -2.166       1.124
63               -1.7826      1.987     -0.897      0.370      -5.681       2.116
70               -0.7331      1.313     -0.558      0.577      -3.309       1.843
73                1.7820      0.647      2.753      0.006       0.512       3.052
75               -2.4782      1.705     -1.453      0.146      -5.823       0.867
78               -4.7277      1.705     -2.773      0.006      -8.072      -1.383
80               -0.6038      1.826     -0.331      0.741      -4.186       2.978
==============================================================================
Omnibus:                      301.724   Durbin-Watson:                   1.111
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             8604.963
Skew:                          -0.199   Prob(JB):                         0.00
Kurtosis:                      14.891   Cond. No.                     3.23e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.11e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column VI
y = data['roa']
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.26885761152559406
                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.269
Model:                            OLS   Adj. R-squared:                  0.243
Method:                 Least Squares   F-statistic:                     10.57
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           6.68e-66
Time:                        10:37:59   Log-Likelihood:                -4322.7
No. Observations:                1459   AIC:                             8745.
Df Residuals:                    1409   BIC:                             9010.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             8.5312      0.845     10.098      0.000       6.874      10.189
founderCEO        5.2533      0.550      9.548      0.000       4.174       6.333
bs_volatility   -13.7068      1.842     -7.440      0.000     -17.321     -10.093
ln(Asset)        -0.3804      0.228     -1.667      0.096      -0.828       0.067
hightech          1.3507      0.308      4.387      0.000       0.747       1.955
1992              0.6284      0.398      1.580      0.114      -0.152       1.408
1993              0.1972      0.345      0.572      0.567      -0.479       0.873
1994              1.2192      0.341      3.572      0.000       0.550       1.889
1995              1.0532      0.336      3.136      0.002       0.394       1.712
1996              0.9276      0.335      2.768      0.006       0.270       1.585
1997              0.9595      0.335      2.863      0.004       0.302       1.617
1998              1.3430      0.349      3.850      0.000       0.659       2.027
1999              2.2032      0.366      6.015      0.000       1.485       2.922
13               -2.5305      1.015     -2.494      0.013      -4.521      -0.540
16               -1.2678      1.230     -1.030      0.303      -3.681       1.146
20                3.4430      0.533      6.457      0.000       2.397       4.489
21                5.1517      1.656      3.111      0.002       1.903       8.400
23                3.2969      1.655      1.992      0.047       0.050       6.544
24                0.2337      1.217      0.192      0.848      -2.154       2.621
25               -1.1393      1.655     -0.689      0.491      -4.385       2.106
26               -0.6390      0.667     -0.958      0.338      -1.947       0.669
27                0.7991      0.624      1.281      0.200      -0.425       2.023
28                4.9784      0.428     11.639      0.000       4.139       5.817
29               -2.2390      0.680     -3.293      0.001      -3.573      -0.905
30                1.6065      0.876      1.833      0.067      -0.113       3.326
32               -3.8209      1.771     -2.157      0.031      -7.296      -0.346
33                0.1205      0.735      0.164      0.870      -1.321       1.562
34               -0.1321      0.770     -0.171      0.864      -1.643       1.379
35               -0.1609      0.447     -0.360      0.719      -1.037       0.715
36                0.8471      0.508      1.669      0.095      -0.149       1.843
37               -0.2566      0.467     -0.549      0.583      -1.172       0.659
38               -0.3447      0.733     -0.470      0.638      -1.783       1.093
39                2.5515      1.011      2.525      0.012       0.569       4.534
40               -1.1149      0.871     -1.279      0.201      -2.824       0.594
42               -2.4542      1.768     -1.388      0.165      -5.923       1.015
45               -1.6175      0.750     -2.158      0.031      -3.088      -0.147
48               -0.8117      0.889     -0.913      0.361      -2.555       0.932
49               -2.4527      1.653     -1.484      0.138      -5.696       0.790
50                2.1548      0.872      2.471      0.014       0.444       3.865
51               -1.5218      0.731     -2.081      0.038      -2.956      -0.087
52                2.3726      1.022      2.321      0.020       0.367       4.378
53               -0.4422      0.676     -0.654      0.513      -1.769       0.885
54                2.4889      0.958      2.598      0.009       0.610       4.368
56                4.9296      0.801      6.157      0.000       3.359       6.500
57                2.8266      1.228      2.301      0.022       0.417       5.236
58                3.4490      1.771      1.948      0.052      -0.024       6.922
59               -0.1968      0.806     -0.244      0.807      -1.777       1.384
63               -3.6204      1.947     -1.859      0.063      -7.440       0.200
70                0.6090      1.264      0.482      0.630      -1.871       3.089
73                1.0091      0.637      1.584      0.113      -0.241       2.259
75               -2.5266      1.660     -1.522      0.128      -5.783       0.730
78               -4.6911      1.660     -2.826      0.005      -7.947      -1.435
80               -0.3561      1.779     -0.200      0.841      -3.845       3.133
==============================================================================
Omnibus:                      327.855   Durbin-Watson:                   1.156
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7929.685
Skew:                          -0.433   Prob(JB):                         0.00
Kurtosis:                      14.388   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column VII
y = data['roa']
X=data[['NonFounderFamily','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.22214612237104825
                            OLS Regression Results
==============================================================================
Dep. Variable:                    roa   R-squared:                       0.222
Model:                            OLS   Adj. R-squared:                  0.195
Method:                 Least Squares   F-statistic:                     8.212
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           6.88e-49
Time:                        10:37:59   Log-Likelihood:                -4367.8
No. Observations:                1459   AIC:                             8836.
Df Residuals:                    1409   BIC:                             9100.
Df Model:                          49
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.1562      0.885      9.213      0.000       6.420       9.893
NonFounderFamily    -0.3457      0.334     -1.036      0.300      -1.000       0.309
bs_volatility      -10.7164      1.873     -5.722      0.000     -14.390      -7.043
ln(Asset)           -0.3549      0.236     -1.503      0.133      -0.818       0.108
hightech             1.4642      0.319      4.585      0.000       0.838       2.091
1992                 0.6215      0.410      1.514      0.130      -0.184       1.427
1993                 0.2252      0.356      0.633      0.527      -0.473       0.923
1994                 1.2259      0.353      3.477      0.001       0.534       1.917
1995                 1.0734      0.347      3.094      0.002       0.393       1.754
1996                 0.9364      0.346      2.705      0.007       0.257       1.616
1997                 0.9510      0.346      2.747      0.006       0.272       1.630
1998                 1.1690      0.360      3.244      0.001       0.462       1.876
1999                 1.9538      0.378      5.172      0.000       1.213       2.695
13                  -2.9476      1.053     -2.800      0.005      -5.012      -0.883
16                  -1.8209      1.273     -1.431      0.153      -4.318       0.676
20                   3.3181      0.551      6.021      0.000       2.237       4.399
21                   4.7187      1.711      2.758      0.006       1.362       8.075
23                   3.2720      1.722      1.900      0.058      -0.106       6.650
24                   0.1734      1.276      0.136      0.892      -2.329       2.676
25                  -1.4848      1.710     -0.868      0.385      -4.839       1.869
26                  -0.6181      0.688     -0.899      0.369      -1.967       0.731
27                   0.7144      0.659      1.084      0.279      -0.578       2.007
28                   4.6914      0.442     10.619      0.000       3.825       5.558
29                  -2.0831      0.702     -2.968      0.003      -3.460      -0.706
30                   3.7091      0.875      4.241      0.000       1.993       5.425
32                  -4.5331      1.828     -2.480      0.013      -8.119      -0.947
33                  -0.2943      0.757     -0.389      0.698      -1.780       1.191
34                  -0.3732      0.794     -0.470      0.639      -1.931       1.185
35                  -0.2830      0.462     -0.612      0.541      -1.190       0.624
36                   0.7492      0.524      1.431      0.153      -0.278       1.776
37                  -0.4232      0.481     -0.879      0.379      -1.367       0.521
38                  -0.8495      0.757     -1.122      0.262      -2.335       0.636
39                   2.0859      1.042      2.003      0.045       0.043       4.129
40                  -1.5008      0.903     -1.661      0.097      -3.273       0.271
42                  -2.7743      1.839     -1.508      0.132      -6.382       0.834
45                  -1.3664      0.777     -1.759      0.079      -2.890       0.157
48                   0.0367      0.912      0.040      0.968      -1.753       1.826
49                  -2.8471      1.707     -1.667      0.096      -6.197       0.502
50                   1.7742      0.898      1.975      0.048       0.012       3.537
51                  -2.0054      0.753     -2.663      0.008      -3.483      -0.528
52                   3.7881      1.046      3.623      0.000       1.737       5.839
53                  -0.3812      0.698     -0.546      0.585      -1.751       0.988
54                   2.3001      0.999      2.302      0.021       0.340       4.260
56                   5.8861      0.825      7.134      0.000       4.267       7.505
57                   2.0758      1.267      1.638      0.102      -0.410       4.562
58                   3.1552      1.829      1.725      0.085      -0.432       6.742
59                   0.2202      0.845      0.261      0.794      -1.437       1.877
63                  -0.9406      1.989     -0.473      0.636      -4.842       2.960
70                   0.3867      1.327      0.291      0.771      -2.217       2.990
73                   1.8475      0.651      2.837      0.005       0.570       3.125
75                  -2.9386      1.714     -1.715      0.087      -6.301       0.424
78                  -5.1916      1.713     -3.030      0.002      -8.553      -1.830
80                  -1.0896      1.835     -0.594      0.553      -4.689       2.509
==============================================================================
Omnibus:                      308.023   Durbin-Watson:                   1.106
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9321.606
Skew:                          -0.201   Prob(JB):                         0.00
Kurtosis:                      15.376   Cond. No.                     3.91e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.43e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column VIII

y = data['ln(Q)']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit(cov_type='HC3')


#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.3629970822430464
                            OLS Regression Results
==============================================================================
Dep. Variable:                  ln(Q)   R-squared:                       0.363
Model:                            OLS   Adj. R-squared:                  0.341
Method:                 Least Squares   F-statistic:                     122.0
Date:                Wed, 04 Aug 2021   Prob (F-statistic):               0.00
Time:                        10:37:59   Log-Likelihood:                -548.89
No. Observations:                1459   AIC:                             1198.
Df Residuals:                    1409   BIC:                             1462.
Df Model:                          49
Covariance Type:                  HC3
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.5794      0.051     11.280      0.000       0.479       0.680
FamFirm           0.0980      0.026      3.758      0.000       0.047       0.149
bs_volatility    -0.5955      0.148     -4.011      0.000      -0.886      -0.305
ln(Asset)        -0.0065      0.012     -0.537      0.591      -0.030       0.017
hightech          0.1509      0.023      6.465      0.000       0.105       0.197
1992              0.0054      0.029      0.185      0.853      -0.051       0.062
1993              0.0048      0.022      0.215      0.830      -0.039       0.048
1994             -0.0426      0.021     -1.990      0.047      -0.084      -0.001
1995              0.0127      0.022      0.571      0.568      -0.031       0.056
1996              0.0557      0.023      2.428      0.015       0.011       0.101
1997              0.1696      0.025      6.746      0.000       0.120       0.219
1998              0.2057      0.031      6.667      0.000       0.145       0.266
1999              0.1682      0.034      4.991      0.000       0.102       0.234
13               -0.0614      0.055     -1.108      0.268      -0.170       0.047
16               -0.0853      0.087     -0.980      0.327      -0.256       0.085
20                0.4395      0.043     10.130      0.000       0.354       0.525
21                0.2741      0.067      4.068      0.000       0.142       0.406
23               -0.0985      0.054     -1.809      0.070      -0.205       0.008
24               -0.0976      0.061     -1.611      0.107      -0.216       0.021
25               -0.2359      0.036     -6.507      0.000      -0.307      -0.165
26               -0.0140      0.054     -0.257      0.797      -0.121       0.093
27                0.0688      0.035      1.990      0.047       0.001       0.137
28                0.4764      0.043     11.190      0.000       0.393       0.560
29               -0.1669      0.029     -5.679      0.000      -0.224      -0.109
30                0.1194      0.063      1.907      0.057      -0.003       0.242
32                0.0492      0.104      0.475      0.635      -0.154       0.252
33               -0.0465      0.062     -0.747      0.455      -0.169       0.076
34                0.0172      0.085      0.203      0.839      -0.149       0.184
35               -0.0696      0.033     -2.138      0.032      -0.133      -0.006
36                0.0067      0.041      0.164      0.870      -0.073       0.087
37               -0.1664      0.021     -7.764      0.000      -0.208      -0.124
38               -0.0829      0.042     -1.993      0.046      -0.164      -0.001
39                0.1143      0.071      1.618      0.106      -0.024       0.253
40               -0.1958      0.036     -5.373      0.000      -0.267      -0.124
42               -0.4574      0.052     -8.854      0.000      -0.559      -0.356
45               -0.2303      0.027     -8.610      0.000      -0.283      -0.178
48                0.1390      0.036      3.873      0.000       0.069       0.209
49               -0.2636      0.021    -12.785      0.000      -0.304      -0.223
50                0.0371      0.066      0.558      0.577      -0.093       0.167
51               -0.1796      0.051     -3.525      0.000      -0.279      -0.080
52                0.5321      0.094      5.633      0.000       0.347       0.717
53               -0.1477      0.046     -3.194      0.001      -0.238      -0.057
54                0.1870      0.062      3.020      0.003       0.066       0.308
56                0.2309      0.080      2.874      0.004       0.073       0.388
57                0.2005      0.090      2.217      0.027       0.023       0.378
58                0.4010      0.051      7.815      0.000       0.300       0.502
59                0.0421      0.064      0.659      0.510      -0.083       0.167
63               -0.0640      0.171     -0.375      0.707      -0.398       0.270
70               -0.0212      0.054     -0.393      0.694      -0.127       0.085
73                0.2968      0.069      4.306      0.000       0.162       0.432
75               -0.3339      0.050     -6.712      0.000      -0.431      -0.236
78                0.1035      0.096      1.074      0.283      -0.085       0.292
80               -0.1375      0.056     -2.436      0.015      -0.248      -0.027
==============================================================================
Omnibus:                      147.376   Durbin-Watson:                   0.540
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              234.844
Skew:                           0.717   Prob(JB):                     1.01e-51
Kurtosis:                       4.343   Cond. No.                     3.23e+16
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The smallest eigenvalue is 2.11e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/usr/local/lib/python3.7/dist-packages/statsmodels/base/model.py:1834: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 52, but rank is 50
  'rank is %d' % (J, J_), ValueWarning)

In [ ]:
#Column IX
y = data['ln(Q)']
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.38614949906553253
                            OLS Regression Results
==============================================================================
Dep. Variable:                  ln(Q)   R-squared:                       0.386
Model:                            OLS   Adj. R-squared:                  0.365
Method:                 Least Squares   F-statistic:                     18.09
Date:                Wed, 04 Aug 2021   Prob (F-statistic):          1.01e-115
Time:                        10:37:59   Log-Likelihood:                -521.88
No. Observations:                1459   AIC:                             1144.
Df Residuals:                    1409   BIC:                             1408.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             0.6614      0.062     10.593      0.000       0.539       0.784
founderCEO        0.3458      0.041      8.505      0.000       0.266       0.426
bs_volatility    -0.7708      0.136     -5.662      0.000      -1.038      -0.504
ln(Asset)        -0.0162      0.017     -0.962      0.336      -0.049       0.017
hightech          0.1331      0.023      5.851      0.000       0.089       0.178
1992              0.0111      0.029      0.376      0.707      -0.047       0.069
1993              0.0100      0.025      0.393      0.694      -0.040       0.060
1994             -0.0360      0.025     -1.427      0.154      -0.085       0.013
1995              0.0189      0.025      0.761      0.447      -0.030       0.068
1996              0.0631      0.025      2.546      0.011       0.014       0.112
1997              0.1780      0.025      7.187      0.000       0.129       0.227
1998              0.2250      0.026      8.729      0.000       0.174       0.276
1999              0.1913      0.027      7.069      0.000       0.138       0.244
13               -0.0832      0.075     -1.110      0.267      -0.230       0.064
16               -0.0976      0.091     -1.074      0.283      -0.276       0.081
20                0.4579      0.039     11.620      0.000       0.381       0.535
21                0.2571      0.122      2.101      0.036       0.017       0.497
23               -0.0204      0.122     -0.167      0.868      -0.260       0.220
24               -0.0172      0.090     -0.191      0.848      -0.194       0.159
25               -0.2566      0.122     -2.098      0.036      -0.496      -0.017
26               -0.0251      0.049     -0.510      0.610      -0.122       0.072
27                0.1217      0.046      2.640      0.008       0.031       0.212
28                0.4774      0.032     15.102      0.000       0.415       0.539
29               -0.1861      0.050     -3.703      0.000      -0.285      -0.088
30                0.0164      0.065      0.254      0.800      -0.111       0.143
32                0.0517      0.131      0.395      0.693      -0.205       0.309
33               -0.0122      0.054     -0.224      0.823      -0.119       0.094
34                0.0384      0.057      0.676      0.499      -0.073       0.150
35               -0.0499      0.033     -1.513      0.131      -0.115       0.015
36                0.0156      0.038      0.416      0.677      -0.058       0.089
37               -0.1591      0.035     -4.610      0.000      -0.227      -0.091
38               -0.0797      0.054     -1.471      0.141      -0.186       0.027
39                0.1473      0.075      1.973      0.049       0.001       0.294
40               -0.2101      0.064     -3.262      0.001      -0.336      -0.084
42               -0.3573      0.131     -2.734      0.006      -0.614      -0.101
45               -0.2700      0.055     -4.875      0.000      -0.379      -0.161
48                0.0967      0.066      1.472      0.141      -0.032       0.226
49               -0.2758      0.122     -2.258      0.024      -0.516      -0.036
50                0.0557      0.064      0.865      0.387      -0.071       0.182
51               -0.1649      0.054     -3.052      0.002      -0.271      -0.059
52                0.4361      0.076      5.772      0.000       0.288       0.584
53               -0.1599      0.050     -3.200      0.001      -0.258      -0.062
54                0.2498      0.071      3.530      0.000       0.111       0.389
56                0.2170      0.059      3.668      0.000       0.101       0.333
57                0.2102      0.091      2.316      0.021       0.032       0.388
58                0.3840      0.131      2.934      0.003       0.127       0.641
59                0.0704      0.060      1.182      0.237      -0.046       0.187
63               -0.1753      0.144     -1.218      0.223      -0.458       0.107
70                0.0775      0.093      0.829      0.407      -0.106       0.261
73                0.2471      0.047      5.249      0.000       0.155       0.339
75               -0.3416      0.123     -2.785      0.005      -0.582      -0.101
78                0.1014      0.123      0.826      0.409      -0.139       0.342
80               -0.1261      0.131     -0.960      0.337      -0.384       0.132
==============================================================================
Omnibus:                      138.075   Durbin-Watson:                   0.552
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              213.366
Skew:                           0.693   Prob(JB):                     4.66e-47
Kurtosis:                       4.261   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column X
y = data['ln(Q)']
X=data[['NonFounderFamily','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.35468100851839024
                            OLS Regression Results
==============================================================================
Dep. Variable:                  ln(Q)   R-squared:                       0.355
Model:                            OLS   Adj. R-squared:                  0.332
Method:                 Least Squares   F-statistic:                     15.80
Date:                Wed, 04 Aug 2021   Prob (F-statistic):          2.72e-101
Time:                        10:37:59   Log-Likelihood:                -558.35
No. Observations:                1459   AIC:                             1217.
Df Residuals:                    1409   BIC:                             1481.
Df Model:                          49
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.6290      0.065      9.673      0.000       0.501       0.757
NonFounderFamily    -0.0075      0.025     -0.306      0.760      -0.056       0.041
bs_volatility       -0.5700      0.138     -4.143      0.000      -0.840      -0.300
ln(Asset)           -0.0137      0.017     -0.788      0.431      -0.048       0.020
hightech             0.1423      0.023      6.067      0.000       0.096       0.188
1992                 0.0100      0.030      0.331      0.741      -0.049       0.069
1993                 0.0110      0.026      0.422      0.673      -0.040       0.062
1994                -0.0364      0.026     -1.404      0.161      -0.087       0.014
1995                 0.0194      0.025      0.759      0.448      -0.031       0.069
1996                 0.0628      0.025      2.467      0.014       0.013       0.113
1997                 0.1765      0.025      6.941      0.000       0.127       0.226
1998                 0.2122      0.026      8.016      0.000       0.160       0.264
1999                 0.1735      0.028      6.253      0.000       0.119       0.228
13                  -0.1054      0.077     -1.363      0.173      -0.257       0.046
16                  -0.1291      0.094     -1.380      0.168      -0.312       0.054
20                   0.4478      0.040     11.061      0.000       0.368       0.527
21                   0.2335      0.126      1.858      0.063      -0.013       0.480
23                  -0.0324      0.126     -0.256      0.798      -0.281       0.216
24                  -0.0316      0.094     -0.337      0.736      -0.215       0.152
25                  -0.2745      0.126     -2.185      0.029      -0.521      -0.028
26                  -0.0232      0.051     -0.459      0.646      -0.122       0.076
27                   0.1095      0.048      2.262      0.024       0.015       0.204
28                   0.4601      0.032     14.177      0.000       0.396       0.524
29                  -0.1743      0.052     -3.381      0.001      -0.275      -0.073
30                   0.1554      0.064      2.418      0.016       0.029       0.281
32                   0.0091      0.134      0.067      0.946      -0.254       0.272
33                  -0.0412      0.056     -0.740      0.459      -0.150       0.068
34                   0.0213      0.058      0.364      0.716      -0.093       0.136
35                  -0.0600      0.034     -1.766      0.078      -0.127       0.007
36                   0.0086      0.038      0.223      0.824      -0.067       0.084
37                  -0.1699      0.035     -4.806      0.000      -0.239      -0.101
38                  -0.1102      0.056     -1.982      0.048      -0.219      -0.001
39                   0.1153      0.077      1.507      0.132      -0.035       0.265
40                  -0.2311      0.066     -3.482      0.001      -0.361      -0.101
42                  -0.3896      0.135     -2.884      0.004      -0.655      -0.125
45                  -0.2496      0.057     -4.374      0.000      -0.362      -0.138
48                   0.1530      0.067      2.283      0.023       0.022       0.284
49                  -0.2976      0.125     -2.373      0.018      -0.544      -0.052
50                   0.0307      0.066      0.465      0.642      -0.099       0.160
51                  -0.1955      0.055     -3.535      0.000      -0.304      -0.087
52                   0.5333      0.077      6.943      0.000       0.383       0.684
53                  -0.1545      0.051     -3.013      0.003      -0.255      -0.054
54                   0.2304      0.073      3.139      0.002       0.086       0.374
56                   0.2760      0.061      4.554      0.000       0.157       0.395
57                   0.1644      0.093      1.766      0.078      -0.018       0.347
58                   0.3689      0.134      2.746      0.006       0.105       0.632
59                   0.0909      0.062      1.464      0.143      -0.031       0.213
63                  -0.0007      0.146     -0.005      0.996      -0.287       0.286
70                   0.0513      0.098      0.526      0.599      -0.140       0.243
73                   0.3039      0.048      6.353      0.000       0.210       0.398
75                  -0.3649      0.126     -2.898      0.004      -0.612      -0.118
78                   0.0721      0.126      0.573      0.567      -0.175       0.319
80                  -0.1710      0.135     -1.269      0.205      -0.435       0.093
==============================================================================
Omnibus:                      160.257   Durbin-Watson:                   0.547
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              263.383
Skew:                           0.755   Prob(JB):                     6.41e-58
Kurtosis:                       4.432   Cond. No.                     3.91e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.43e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Column XI, data filterred for variable FarFirm such that FarFirm = 0

y = data['Q']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit(cov_type='HC3')


#Print the regression coefficients
#results.params
#results.tvalues
#R2 = print(results.rsquared)

#print(results.summary())

In [ ]:
#Column XII


y = data['Q']
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.290
Method:                 Least Squares   F-statistic:                     13.14
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.18e-83
Time:                        10:37:59   Log-Likelihood:                -2124.0
No. Observations:                1459   AIC:                             4348.
Df Residuals:                    1409   BIC:                             4612.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.9234      0.187     10.274      0.000       1.556       2.291
founderCEO        0.9827      0.122      8.061      0.000       0.744       1.222
bs_volatility    -1.0657      0.408     -2.611      0.009      -1.866      -0.265
ln(Asset)        -0.0476      0.051     -0.942      0.347      -0.147       0.052
hightech          0.3263      0.068      4.783      0.000       0.192       0.460
1992              0.0266      0.088      0.302      0.763      -0.146       0.199
1993             -0.0089      0.076     -0.116      0.907      -0.159       0.141
1994             -0.0830      0.076     -1.098      0.273      -0.231       0.065
1995              0.0535      0.074      0.719      0.472      -0.092       0.200
1996              0.1662      0.074      2.238      0.025       0.021       0.312
1997              0.4650      0.074      6.261      0.000       0.319       0.611
1998              0.6713      0.077      8.686      0.000       0.520       0.823
1999              0.6327      0.081      7.795      0.000       0.473       0.792
13               -0.1785      0.225     -0.794      0.428      -0.620       0.263
16               -0.2243      0.273     -0.823      0.411      -0.759       0.310
20                1.1742      0.118      9.938      0.000       0.942       1.406
21                0.4230      0.367      1.153      0.249      -0.297       1.143
23               -0.1108      0.367     -0.302      0.763      -0.830       0.609
24               -0.0851      0.270     -0.316      0.752      -0.614       0.444
25               -0.4683      0.367     -1.277      0.202      -1.187       0.251
26               -0.0035      0.148     -0.024      0.981      -0.293       0.286
27                0.1843      0.138      1.333      0.183      -0.087       0.455
28                1.3684      0.095     14.438      0.000       1.183       1.554
29               -0.3712      0.151     -2.463      0.014      -0.667      -0.076
30               -0.1732      0.194     -0.892      0.373      -0.554       0.208
32               -0.0293      0.392     -0.075      0.941      -0.799       0.741
33                0.0400      0.163      0.246      0.806      -0.279       0.359
34                0.2426      0.171      1.422      0.155      -0.092       0.577
35               -0.2081      0.099     -2.103      0.036      -0.402      -0.014
36               -0.0013      0.112     -0.011      0.991      -0.222       0.219
37               -0.3245      0.103     -3.137      0.002      -0.527      -0.122
38               -0.2504      0.162     -1.542      0.123      -0.569       0.068
39                0.2399      0.224      1.071      0.284      -0.199       0.679
40               -0.3751      0.193     -1.943      0.052      -0.754       0.004
42               -0.5747      0.392     -1.467      0.143      -1.343       0.194
45               -0.5558      0.166     -3.347      0.001      -0.882      -0.230
48                0.0289      0.197      0.147      0.883      -0.357       0.415
49               -0.4705      0.366     -1.284      0.199      -1.189       0.248
50                0.1347      0.193      0.697      0.486      -0.244       0.514
51               -0.2445      0.162     -1.509      0.132      -0.562       0.073
52                1.1276      0.227      4.977      0.000       0.683       1.572
53               -0.2684      0.150     -1.791      0.074      -0.562       0.026
54                0.4778      0.212      2.251      0.025       0.061       0.894
56                0.5427      0.177      3.059      0.002       0.195       0.891
57                0.4003      0.272      1.471      0.142      -0.134       0.934
58                0.7442      0.392      1.897      0.058      -0.026       1.514
59                0.1652      0.179      0.925      0.355      -0.185       0.515
63               -0.6458      0.432     -1.497      0.135      -1.492       0.201
70                0.0509      0.280      0.182      0.856      -0.499       0.600
73                0.7861      0.141      5.568      0.000       0.509       1.063
75               -0.5419      0.368     -1.473      0.141      -1.263       0.180
78                0.1723      0.368      0.469      0.639      -0.549       0.894
80               -0.2745      0.394     -0.697      0.486      -1.048       0.499
==============================================================================
Omnibus:                     1057.289   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            29838.921
Skew:                           3.032   Prob(JB):                         0.00
Kurtosis:                      24.309   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
Column XIII, include firm dummies for column I

In [ ]:
y = data['Q']
X=data[['FamFirm','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['ticker']))               
X = sm.add_constant(X)
model = sm.OLS(y,X.astype(float))
#results = model.fit(cov_type='HC3')


#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.290
Method:                 Least Squares   F-statistic:                     13.14
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.18e-83
Time:                        13:53:47   Log-Likelihood:                -2124.0
No. Observations:                1459   AIC:                             4348.
Df Residuals:                    1409   BIC:                             4612.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.9234      0.187     10.274      0.000       1.556       2.291
founderCEO        0.9827      0.122      8.061      0.000       0.744       1.222
bs_volatility    -1.0657      0.408     -2.611      0.009      -1.866      -0.265
ln(Asset)        -0.0476      0.051     -0.942      0.347      -0.147       0.052
hightech          0.3263      0.068      4.783      0.000       0.192       0.460
1992              0.0266      0.088      0.302      0.763      -0.146       0.199
1993             -0.0089      0.076     -0.116      0.907      -0.159       0.141
1994             -0.0830      0.076     -1.098      0.273      -0.231       0.065
1995              0.0535      0.074      0.719      0.472      -0.092       0.200
1996              0.1662      0.074      2.238      0.025       0.021       0.312
1997              0.4650      0.074      6.261      0.000       0.319       0.611
1998              0.6713      0.077      8.686      0.000       0.520       0.823
1999              0.6327      0.081      7.795      0.000       0.473       0.792
13               -0.1785      0.225     -0.794      0.428      -0.620       0.263
16               -0.2243      0.273     -0.823      0.411      -0.759       0.310
20                1.1742      0.118      9.938      0.000       0.942       1.406
21                0.4230      0.367      1.153      0.249      -0.297       1.143
23               -0.1108      0.367     -0.302      0.763      -0.830       0.609
24               -0.0851      0.270     -0.316      0.752      -0.614       0.444
25               -0.4683      0.367     -1.277      0.202      -1.187       0.251
26               -0.0035      0.148     -0.024      0.981      -0.293       0.286
27                0.1843      0.138      1.333      0.183      -0.087       0.455
28                1.3684      0.095     14.438      0.000       1.183       1.554
29               -0.3712      0.151     -2.463      0.014      -0.667      -0.076
30               -0.1732      0.194     -0.892      0.373      -0.554       0.208
32               -0.0293      0.392     -0.075      0.941      -0.799       0.741
33                0.0400      0.163      0.246      0.806      -0.279       0.359
34                0.2426      0.171      1.422      0.155      -0.092       0.577
35               -0.2081      0.099     -2.103      0.036      -0.402      -0.014
36               -0.0013      0.112     -0.011      0.991      -0.222       0.219
37               -0.3245      0.103     -3.137      0.002      -0.527      -0.122
38               -0.2504      0.162     -1.542      0.123      -0.569       0.068
39                0.2399      0.224      1.071      0.284      -0.199       0.679
40               -0.3751      0.193     -1.943      0.052      -0.754       0.004
42               -0.5747      0.392     -1.467      0.143      -1.343       0.194
45               -0.5558      0.166     -3.347      0.001      -0.882      -0.230
48                0.0289      0.197      0.147      0.883      -0.357       0.415
49               -0.4705      0.366     -1.284      0.199      -1.189       0.248
50                0.1347      0.193      0.697      0.486      -0.244       0.514
51               -0.2445      0.162     -1.509      0.132      -0.562       0.073
52                1.1276      0.227      4.977      0.000       0.683       1.572
53               -0.2684      0.150     -1.791      0.074      -0.562       0.026
54                0.4778      0.212      2.251      0.025       0.061       0.894
56                0.5427      0.177      3.059      0.002       0.195       0.891
57                0.4003      0.272      1.471      0.142      -0.134       0.934
58                0.7442      0.392      1.897      0.058      -0.026       1.514
59                0.1652      0.179      0.925      0.355      -0.185       0.515
63               -0.6458      0.432     -1.497      0.135      -1.492       0.201
70                0.0509      0.280      0.182      0.856      -0.499       0.600
73                0.7861      0.141      5.568      0.000       0.509       1.063
75               -0.5419      0.368     -1.473      0.141      -1.263       0.180
78                0.1723      0.368      0.469      0.639      -0.549       0.894
80               -0.2745      0.394     -0.697      0.486      -1.048       0.499
==============================================================================
Omnibus:                     1057.289   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            29838.921
Skew:                           3.032   Prob(JB):                         0.00
Kurtosis:                      24.309   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Part 5: Instrumental Variables
#Set Up Y variable
#from statsmodels.sandbox.regression.gmm import IV2SLS

In [ ]:
#Run The Regression


#iv_1 = IV2SLS(exog=pd.concat([data['bs_volatility'], data['ln(Asset)'] , data['hightech']]), endog=(data['founderCEO']), instrument = data['meanagef']).fit()
#res_2sls = iv_1.fit()
#print(res_2sls)
#print(print(iv1.summary))


#resultIV.spec_hausman()
#Source: https://stats.stackexchange.com/questions/210696/how-to-interpret-hausman-test-results

# IV 2SLS Regression

In [ ]:
#First stage of the IV 2 stage regression
y = data['founderCEO']
X = data['meanagef']
X = sm.add_constant(X)

model = sm.OLS(y,X)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             founderCEO   R-squared:                       0.530
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     1645.
Date:                Wed, 04 Aug 2021   Prob (F-statistic):          2.47e-241
Time:                        10:38:00   Log-Likelihood:                 448.82
No. Observations:                1459   AIC:                            -893.6
Df Residuals:                    1457   BIC:                            -883.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.5270      0.036     42.228      0.000       1.456       1.598
meanagef      -0.0161      0.000    -40.557      0.000      -0.017      -0.015
==============================================================================
Omnibus:                      308.814   Durbin-Watson:                   0.496
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5638.885
Skew:                           0.470   Prob(JB):                         0.00
Kurtosis:                      12.585   Cond. No.                         707.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
print(data['founderCEO'])

0       0
1       0
2       0
3       0
4       0
       ..
1461    0
1462    0
1463    0
1464    0
1465    0
Name: founderCEO, Length: 1459, dtype: int64

In [ ]:
Predicted = result.predict()
print(Predicted)

[-0.00142703 -0.00142703 -0.00142703 ... -0.00142703 -0.00142703
 -0.00142703]

In [ ]:
data['Predicted'] = Predicted

In [ ]:
#Second stage of IV regression: Regressing Q on the exogenous variables and the predicted value of instrumented variable (founderCEO). The result is close to the iv 2SLS regression coming below.

y = data['Q']
X = data[['bs_volatility','ln(Asset)','hightech']].join(data['Predicted'])
X = sm.add_constant(X)

model = sm.OLS(y,X)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.067
Model:                            OLS   Adj. R-squared:                  0.064
Method:                 Least Squares   F-statistic:                     25.91
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           9.01e-21
Time:                        12:22:23   Log-Likelihood:                -2348.3
No. Observations:                1459   AIC:                             4707.
Df Residuals:                    1454   BIC:                             4733.
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             3.2768      0.192     17.087      0.000       2.901       3.653
bs_volatility    -1.8633      0.404     -4.615      0.000      -2.655      -1.071
ln(Asset)        -0.2426      0.049     -4.956      0.000      -0.339      -0.147
hightech          0.1170      0.085      1.373      0.170      -0.050       0.284
Predicted         1.7157      0.186      9.243      0.000       1.352       2.080
==============================================================================
Omnibus:                     1120.312   Durbin-Watson:                   0.608
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            26071.416
Skew:                           3.399   Prob(JB):                         0.00
Kurtosis:                      22.562   Cond. No.                         50.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.



```
# 
```

# Estimating correlation between residuals from column III regression with the IV variable meanagef

In [ ]:
#Column I

y = data['Q']
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X.astype(float))
results = model.fit()


#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

residuals = results.resid
print(residuals)

0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.290
Method:                 Least Squares   F-statistic:                     13.14
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.18e-83
Time:                        12:29:37   Log-Likelihood:                -2124.0
No. Observations:                1459   AIC:                             4348.
Df Residuals:                    1409   BIC:                             4612.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.9234      0.187     10.274      0.000       1.556       2.291
founderCEO        0.9827      0.122      8.061      0.000       0.744       1.222
bs_volatility    -1.0657      0.408     -2.611      0.009      -1.866      -0.265
ln(Asset)        -0.0476      0.051     -0.942      0.347      -0.147       0.052
hightech          0.3263      0.068      4.783      0.000       0.192       0.460
1992              0.0266      0.088      0.302      0.763      -0.146       0.199
1993             -0.0089      0.076     -0.116      0.907      -0.159       0.141
1994             -0.0830      0.076     -1.098      0.273      -0.231       0.065
1995              0.0535      0.074      0.719      0.472      -0.092       0.200
1996              0.1662      0.074      2.238      0.025       0.021       0.312
1997              0.4650      0.074      6.261      0.000       0.319       0.611
1998              0.6713      0.077      8.686      0.000       0.520       0.823
1999              0.6327      0.081      7.795      0.000       0.473       0.792
13               -0.1785      0.225     -0.794      0.428      -0.620       0.263
16               -0.2243      0.273     -0.823      0.411      -0.759       0.310
20                1.1742      0.118      9.938      0.000       0.942       1.406
21                0.4230      0.367      1.153      0.249      -0.297       1.143
23               -0.1108      0.367     -0.302      0.763      -0.830       0.609
24               -0.0851      0.270     -0.316      0.752      -0.614       0.444
25               -0.4683      0.367     -1.277      0.202      -1.187       0.251
26               -0.0035      0.148     -0.024      0.981      -0.293       0.286
27                0.1843      0.138      1.333      0.183      -0.087       0.455
28                1.3684      0.095     14.438      0.000       1.183       1.554
29               -0.3712      0.151     -2.463      0.014      -0.667      -0.076
30               -0.1732      0.194     -0.892      0.373      -0.554       0.208
32               -0.0293      0.392     -0.075      0.941      -0.799       0.741
33                0.0400      0.163      0.246      0.806      -0.279       0.359
34                0.2426      0.171      1.422      0.155      -0.092       0.577
35               -0.2081      0.099     -2.103      0.036      -0.402      -0.014
36               -0.0013      0.112     -0.011      0.991      -0.222       0.219
37               -0.3245      0.103     -3.137      0.002      -0.527      -0.122
38               -0.2504      0.162     -1.542      0.123      -0.569       0.068
39                0.2399      0.224      1.071      0.284      -0.199       0.679
40               -0.3751      0.193     -1.943      0.052      -0.754       0.004
42               -0.5747      0.392     -1.467      0.143      -1.343       0.194
45               -0.5558      0.166     -3.347      0.001      -0.882      -0.230
48                0.0289      0.197      0.147      0.883      -0.357       0.415
49               -0.4705      0.366     -1.284      0.199      -1.189       0.248
50                0.1347      0.193      0.697      0.486      -0.244       0.514
51               -0.2445      0.162     -1.509      0.132      -0.562       0.073
52                1.1276      0.227      4.977      0.000       0.683       1.572
53               -0.2684      0.150     -1.791      0.074      -0.562       0.026
54                0.4778      0.212      2.251      0.025       0.061       0.894
56                0.5427      0.177      3.059      0.002       0.195       0.891
57                0.4003      0.272      1.471      0.142      -0.134       0.934
58                0.7442      0.392      1.897      0.058      -0.026       1.514
59                0.1652      0.179      0.925      0.355      -0.185       0.515
63               -0.6458      0.432     -1.497      0.135      -1.492       0.201
70                0.0509      0.280      0.182      0.856      -0.499       0.600
73                0.7861      0.141      5.568      0.000       0.509       1.063
75               -0.5419      0.368     -1.473      0.141      -1.263       0.180
78                0.1723      0.368      0.469      0.639      -0.549       0.894
80               -0.2745      0.394     -0.697      0.486      -1.048       0.499
==============================================================================
Omnibus:                     1057.289   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            29838.921
Skew:                           3.032   Prob(JB):                         0.00
Kurtosis:                      24.309   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
0      -0.049693
1      -0.041763
2       0.112007
3       0.024816
4       0.032400
          ...
1461   -0.915994
1462   -0.649833
1463   -0.794263
1464   -1.575089
1465   -1.467224
Length: 1459, dtype: float64

In [ ]:
#Correlation coeffcient
np.corrcoef(residuals,data['meanagef'])

array([[ 1.        , -0.10885844],
       [-0.10885844,  1.        ]])

In [ ]:
#Instrumental Variables Estimation with a constant using built in function of 2sls
y = data['Q']
data['constant'] = 1

instrument = data['meanagef']
endog = data['founderCEO']
exog = data[['constant','bs_volatility', 'ln(Asset)', 'hightech']]

iv = IV2SLS(y,exog, endog,instrument)

result = iv.fit()

print(result.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:                      Q   R-squared:                      0.0246
Estimator:                    IV-2SLS   Adj. R-squared:                 0.0219
No. Observations:                1459   F-statistic:                    109.54
Date:                Wed, Aug 04 2021   P-value (F-stat)                0.0000
Time:                        10:38:00   Distribution:                  chi2(4)
Cov. Estimator:                robust

                               Parameter Estimates
=================================================================================
               Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------
constant          3.0692     0.1641     18.705     0.0000      2.7476      3.3908
bs_volatility    -2.0154     0.3884    -5.1893     0.0000     -2.7766     -1.2542
ln(Asset)        -0.1746     0.0337    -5.1837     0.0000     -0.2406     -0.1086
hightech          0.1432     0.0740     1.9355     0.0529     -0.0018      0.2882
founderCEO        1.6623     0.2666     6.2352     0.0000      1.1398      2.1848
=================================================================================

Endogenous: founderCEO
Instruments: meanagef
Robust Covariance (Heteroskedastic)
Debiased: False

In [ ]:
pd.get_dummies(data['year'])

      1992  1993  1994  1995  1996  1997  1998  1999
0        1     0     0     0     0     0     0     0
1        0     1     0     0     0     0     0     0
2        0     0     1     0     0     0     0     0
3        0     0     0     1     0     0     0     0
4        0     0     0     0     1     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...
1461     0     0     0     1     0     0     0     0
1462     0     0     0     0     1     0     0     0
1463     0     0     0     0     0     1     0     0
1464     0     0     0     0     0     0     1     0
1465     0     0     0     0     0     0     0     1

[1459 rows x 8 columns]

In [ ]:
pd.get_dummies(data['digit2_in'])

      13  16  20  21  23  24  25  26  27  ...  57  58  59  63  70  73  75  78  80
0      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
2      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
3      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
4      0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
1461   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1462   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1463   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1464   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0
1465   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0   0

[1459 rows x 40 columns]

In [ ]:
X=data[['founderCEO','bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
X = sm.add_constant(X)
model = sm.OLS(y,X)
results = model.fit()

#Print the regression coefficients
results.params
results.tvalues
R2 = print(results.rsquared)

print(results.summary())

0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.314
Model:                            OLS   Adj. R-squared:                  0.290
Method:                 Least Squares   F-statistic:                     13.14
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           1.18e-83
Time:                        10:38:00   Log-Likelihood:                -2124.0
No. Observations:                1459   AIC:                             4348.
Df Residuals:                    1409   BIC:                             4612.
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.9234      0.187     10.274      0.000       1.556       2.291
founderCEO        0.9827      0.122      8.061      0.000       0.744       1.222
bs_volatility    -1.0657      0.408     -2.611      0.009      -1.866      -0.265
ln(Asset)        -0.0476      0.051     -0.942      0.347      -0.147       0.052
hightech          0.3263      0.068      4.783      0.000       0.192       0.460
1992              0.0266      0.088      0.302      0.763      -0.146       0.199
1993             -0.0089      0.076     -0.116      0.907      -0.159       0.141
1994             -0.0830      0.076     -1.098      0.273      -0.231       0.065
1995              0.0535      0.074      0.719      0.472      -0.092       0.200
1996              0.1662      0.074      2.238      0.025       0.021       0.312
1997              0.4650      0.074      6.261      0.000       0.319       0.611
1998              0.6713      0.077      8.686      0.000       0.520       0.823
1999              0.6327      0.081      7.795      0.000       0.473       0.792
13               -0.1785      0.225     -0.794      0.428      -0.620       0.263
16               -0.2243      0.273     -0.823      0.411      -0.759       0.310
20                1.1742      0.118      9.938      0.000       0.942       1.406
21                0.4230      0.367      1.153      0.249      -0.297       1.143
23               -0.1108      0.367     -0.302      0.763      -0.830       0.609
24               -0.0851      0.270     -0.316      0.752      -0.614       0.444
25               -0.4683      0.367     -1.277      0.202      -1.187       0.251
26               -0.0035      0.148     -0.024      0.981      -0.293       0.286
27                0.1843      0.138      1.333      0.183      -0.087       0.455
28                1.3684      0.095     14.438      0.000       1.183       1.554
29               -0.3712      0.151     -2.463      0.014      -0.667      -0.076
30               -0.1732      0.194     -0.892      0.373      -0.554       0.208
32               -0.0293      0.392     -0.075      0.941      -0.799       0.741
33                0.0400      0.163      0.246      0.806      -0.279       0.359
34                0.2426      0.171      1.422      0.155      -0.092       0.577
35               -0.2081      0.099     -2.103      0.036      -0.402      -0.014
36               -0.0013      0.112     -0.011      0.991      -0.222       0.219
37               -0.3245      0.103     -3.137      0.002      -0.527      -0.122
38               -0.2504      0.162     -1.542      0.123      -0.569       0.068
39                0.2399      0.224      1.071      0.284      -0.199       0.679
40               -0.3751      0.193     -1.943      0.052      -0.754       0.004
42               -0.5747      0.392     -1.467      0.143      -1.343       0.194
45               -0.5558      0.166     -3.347      0.001      -0.882      -0.230
48                0.0289      0.197      0.147      0.883      -0.357       0.415
49               -0.4705      0.366     -1.284      0.199      -1.189       0.248
50                0.1347      0.193      0.697      0.486      -0.244       0.514
51               -0.2445      0.162     -1.509      0.132      -0.562       0.073
52                1.1276      0.227      4.977      0.000       0.683       1.572
53               -0.2684      0.150     -1.791      0.074      -0.562       0.026
54                0.4778      0.212      2.251      0.025       0.061       0.894
56                0.5427      0.177      3.059      0.002       0.195       0.891
57                0.4003      0.272      1.471      0.142      -0.134       0.934
58                0.7442      0.392      1.897      0.058      -0.026       1.514
59                0.1652      0.179      0.925      0.355      -0.185       0.515
63               -0.6458      0.432     -1.497      0.135      -1.492       0.201
70                0.0509      0.280      0.182      0.856      -0.499       0.600
73                0.7861      0.141      5.568      0.000       0.509       1.063
75               -0.5419      0.368     -1.473      0.141      -1.263       0.180
78                0.1723      0.368      0.469      0.639      -0.549       0.894
80               -0.2745      0.394     -0.697      0.486      -1.048       0.499
==============================================================================
Omnibus:                     1057.289   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            29838.921
Skew:                           3.032   Prob(JB):                         0.00
Kurtosis:                      24.309   Cond. No.                     2.80e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

# Hausman Test

In [ ]:
#####################################Step 1:
#Run regression of endogeneous variable "founderCEO" on and exogeneous varaibles (data[['bs_volatility','ln(Asset)','hightech']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))), instrument founder age meanagef

y = data['founderCEO']
X=data[['bs_volatility','ln(Asset)','hightech','meanagef']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in'])) 
X = sm.add_constant(X)
model = sm.OLS(y,X)
result1 = model.fit()
residual = result1.resid

print(results.params)
print(results.tvalues)
R2 = print(results.rsquared)

result1.params
result1.tvalues
print(result1.summary())

const            1.923434
founderCEO       0.982734
bs_volatility   -1.065685
ln(Asset)       -0.047599
hightech         0.326327
1992             0.026584
1993            -0.008874
1994            -0.083030
1995             0.053542
1996             0.166234
1997             0.464980
1998             0.671339
1999             0.632658
13              -0.178458
16              -0.224348
20               1.174163
21               0.422956
23              -0.110792
24              -0.085103
25              -0.468266
26              -0.003540
27               0.184275
28               1.368435
29              -0.371155
30              -0.173210
32              -0.029288
33               0.040006
34               0.242575
35              -0.208061
36              -0.001272
37              -0.324530
38              -0.250428
39               0.239939
40              -0.375134
42              -0.574696
45              -0.555839
48               0.028945
49              -0.470474
50               0.134664
51              -0.244488
52               1.127617
53              -0.268386
54               0.477812
56               0.542701
57               0.400286
58               0.744162
59               0.165228
63              -0.645791
70               0.050919
73               0.786088
75              -0.541905
78               0.172340
80              -0.274516
dtype: float64
const            10.274172
founderCEO        8.060636
bs_volatility    -2.610632
ln(Asset)        -0.941527
hightech          4.783312
1992              0.301684
1993             -0.116239
1994             -1.097690
1995              0.719456
1996              2.238306
1997              6.261440
1998              8.685599
1999              7.795300
13               -0.793634
16               -0.822851
20                9.937663
21                1.152636
23               -0.302085
24               -0.315526
25               -1.277181
26               -0.023957
27                1.332932
28               14.437778
29               -2.463272
30               -0.892013
32               -0.074621
33                0.245737
34                1.421549
35               -2.102866
36               -0.011312
37               -3.136950
38               -1.541531
39                1.071380
40               -1.942806
42               -1.466687
45               -3.346757
48                0.146955
49               -1.284259
50                0.696989
51               -1.508913
52                4.977296
53               -1.790811
54                2.251233
56                3.058841
57                1.470797
58                1.896651
59                0.925425
63               -1.496616
70                0.181750
73                5.568223
75               -1.473235
78                0.468538
80               -0.696544
dtype: float64
0.31358723185075443
                            OLS Regression Results
==============================================================================
Dep. Variable:             founderCEO   R-squared:                       0.625
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                     47.95
Date:                Wed, 04 Aug 2021   Prob (F-statistic):          1.07e-261
Time:                        10:38:00   Log-Likelihood:                 613.32
No. Observations:                1459   AIC:                            -1127.
Df Residuals:                    1409   BIC:                            -862.4
Df Model:                          49
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             1.4817      0.050     29.381      0.000       1.383       1.581
bs_volatility    -0.0202      0.064     -0.317      0.751      -0.145       0.105
ln(Asset)        -0.0388      0.008     -4.949      0.000      -0.054      -0.023
hightech          0.0436      0.010      4.172      0.000       0.023       0.064
meanagef         -0.0165      0.000    -38.189      0.000      -0.017      -0.016
1992              0.1940      0.014     13.419      0.000       0.166       0.222
1993              0.2062      0.013     16.033      0.000       0.181       0.231
1994              0.2012      0.013     15.777      0.000       0.176       0.226
1995              0.1903      0.012     15.301      0.000       0.166       0.215
1996              0.1797      0.012     14.569      0.000       0.155       0.204
1997              0.1797      0.012     14.535      0.000       0.155       0.204
1998              0.1641      0.013     12.665      0.000       0.139       0.190
1999              0.1665      0.014     12.185      0.000       0.140       0.193
13                0.0018      0.034      0.052      0.958      -0.066       0.069
16                0.0122      0.042      0.292      0.770      -0.070       0.094
20                0.0179      0.018      0.990      0.322      -0.018       0.054
21                0.0213      0.056      0.379      0.705      -0.089       0.132
23                0.0244      0.056      0.434      0.664      -0.086       0.135
24                0.0269      0.041      0.650      0.516      -0.054       0.108
25                0.0275      0.056      0.489      0.625      -0.083       0.138
26                0.0163      0.023      0.721      0.471      -0.028       0.061
27                0.0306      0.021      1.438      0.151      -0.011       0.072
28                0.0319      0.015      2.179      0.030       0.003       0.061
29                0.0693      0.023      3.004      0.003       0.024       0.115
30                0.2460      0.029      8.462      0.000       0.189       0.303
32                0.0408      0.060      0.677      0.499      -0.077       0.159
33                0.0035      0.025      0.140      0.888      -0.046       0.053
34                0.0398      0.026      1.516      0.130      -0.012       0.091
35               -0.0991      0.015     -6.501      0.000      -0.129      -0.069
36                0.0389      0.017      2.248      0.025       0.005       0.073
37                0.0433      0.016      2.712      0.007       0.012       0.075
38             1.087e-05      0.025      0.000      1.000      -0.049       0.049
39               -0.0486      0.034     -1.419      0.156      -0.116       0.019
40                0.0445      0.030      1.499      0.134      -0.014       0.103
42                0.0510      0.060      0.848      0.397      -0.067       0.169
45                0.0985      0.025      3.873      0.000       0.049       0.148
48                0.1850      0.030      6.163      0.000       0.126       0.244
49                0.0538      0.056      0.957      0.338      -0.056       0.164
50               -0.0068      0.030     -0.231      0.818      -0.065       0.051
51                0.0063      0.025      0.252      0.801      -0.043       0.055
52                0.1953      0.034      5.682      0.000       0.128       0.263
53                0.0724      0.023      3.147      0.002       0.027       0.117
54                0.0056      0.033      0.172      0.864      -0.058       0.069
56                0.0824      0.027      3.044      0.002       0.029       0.136
57                0.0626      0.042      1.494      0.135      -0.020       0.145
58                0.0060      0.060      0.100      0.920      -0.112       0.124
59               -0.0019      0.027     -0.068      0.946      -0.056       0.052
63                0.4671      0.065      7.139      0.000       0.339       0.595
70                0.0392      0.043      0.910      0.363      -0.045       0.124
73                0.1038      0.021      4.836      0.000       0.062       0.146
75               -0.1767      0.056     -3.133      0.002      -0.287      -0.066
78                0.0725      0.056      1.283      0.200      -0.038       0.183
80               -0.4234      0.061     -6.960      0.000      -0.543      -0.304
==============================================================================
Omnibus:                      325.673   Durbin-Watson:                   0.554
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5410.458
Skew:                           0.570   Prob(JB):                         0.00
Kurtosis:                      12.365   Cond. No.                     1.55e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.08e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#y = data['founderCEO']
#X=data[['bs_volatility','ln(Asset)','hightech','meanagef']].join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in']))               
#X = sm.add_constant(X)
#model = sm.OLS(y,X)
#results = model.fit()

#Print the regression coefficients
#print(results.summary())

In [ ]:
#Step 2
residual = result1.resid
print(residual)

0       0.251772
1       0.241227
2       0.248567
3       0.263079
4       0.273058
          ...
1461   -0.027079
1462   -0.015396
1463   -0.014835
1464    0.002178
1465    0.001093
Length: 1459, dtype: float64

In [ ]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1461    0
1462    0
1463    0
1464    0
1465    0
Name: founderCEO, Length: 1459, dtype: int64

In [ ]:
print(X)

      const  bs_volatility  ln(Asset)  hightech  meanagef  ...  70  73  75  78  80
0       1.0          0.246   9.307748         0      95.0  ...   0   0   0   0   0
1       1.0          0.228   9.358493         0      95.0  ...   0   0   0   0   0
2       1.0          0.222   9.421670         0      95.0  ...   0   0   0   0   0
3       1.0          0.213   9.521011         0      95.0  ...   0   0   0   0   0
4       1.0          0.206   9.506727         0      95.0  ...   0   0   0   0   0
...     ...            ...        ...       ...       ...  ...  ..  ..  ..  ..  ..
1461    1.0          0.315   4.025352         0      95.0  ...   0   0   0   0   0
1462    1.0          0.365   4.025352         0      95.0  ...   0   0   0   0   0
1463    1.0          0.396   4.025352         0      95.0  ...   0   0   0   0   0
1464    1.0          0.466   4.025352         0      95.0  ...   0   0   0   0   0
1465    1.0          0.530   4.025352         0      95.0  ...   0   0   0   0   0

[1459 rows x 53 columns]

In [ ]:
data['residual'] = residual
X =data[['bs_volatility','ln(Asset)','hightech']].join(data['residual'])
X

      bs_volatility  ln(Asset)  hightech  residual
0             0.246   9.307748         0  0.251772
1             0.228   9.358493         0  0.241227
2             0.222   9.421670         0  0.248567
3             0.213   9.521011         0  0.263079
4             0.206   9.506727         0  0.273058
...             ...        ...       ...       ...
1461          0.315   4.025352         0 -0.027079
1462          0.365   4.025352         0 -0.015396
1463          0.396   4.025352         0 -0.014835
1464          0.466   4.025352         0  0.002178
1465          0.530   4.025352         0  0.001093

[1459 rows x 4 columns]

In [ ]:
#Step 3 and check coeeficient on the residuals Include dummies
y = data['Q']
X =data[['bs_volatility','ln(Asset)','founderCEO','hightech']].join(data['residual']).join(pd.get_dummies(data['year'])).join(pd.get_dummies(data['digit2_in'])) 
X = sm.add_constant(X)

model = sm.OLS(y,X)
results = model.fit() 
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Q   R-squared:                       0.337
Model:                            OLS   Adj. R-squared:                  0.314
Method:                 Least Squares   F-statistic:                     14.33
Date:                Wed, 04 Aug 2021   Prob (F-statistic):           4.38e-93
Time:                        10:38:00   Log-Likelihood:                -2098.4
No. Observations:                1459   AIC:                             4299.
Df Residuals:                    1408   BIC:                             4568.
Df Model:                          50
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             2.0106      0.184     10.902      0.000       1.649       2.372
bs_volatility    -1.5560      0.407     -3.822      0.000      -2.355      -0.757
ln(Asset)        -0.0548      0.050     -1.103      0.270      -0.152       0.043
founderCEO        1.8188      0.168     10.824      0.000       1.489       2.148
hightech          0.3021      0.067      4.499      0.000       0.170       0.434
residual         -1.7015      0.240     -7.098      0.000      -2.172      -1.231
1992              0.0299      0.087      0.346      0.730      -0.140       0.200
1993             -0.0104      0.075     -0.138      0.890      -0.158       0.137
1994             -0.0812      0.074     -1.092      0.275      -0.227       0.065
1995              0.0534      0.073      0.730      0.466      -0.090       0.197
1996              0.1680      0.073      2.301      0.022       0.025       0.311
1997              0.4696      0.073      6.433      0.000       0.326       0.613
1998              0.7040      0.076      9.249      0.000       0.555       0.853
1999              0.6774      0.080      8.465      0.000       0.520       0.834
13               -0.1312      0.221     -0.593      0.553      -0.565       0.303
16               -0.1542      0.268     -0.575      0.565      -0.680       0.372
20                1.2006      0.116     10.333      0.000       0.973       1.429
21                0.4743      0.361      1.315      0.189      -0.233       1.182
23               -0.0694      0.361     -0.193      0.847      -0.777       0.638
24               -0.0379      0.265     -0.143      0.886      -0.558       0.482
25               -0.4308      0.360     -1.195      0.232      -1.138       0.276
26               -0.0089      0.145     -0.061      0.951      -0.294       0.276
27                0.2215      0.136      1.629      0.104      -0.045       0.488
28                1.4082      0.093     15.089      0.000       1.225       1.591
29               -0.4014      0.148     -2.709      0.007      -0.692      -0.111
30               -0.5097      0.197     -2.592      0.010      -0.896      -0.124
32                0.0690      0.386      0.179      0.858      -0.688       0.826
33                0.1121      0.160      0.699      0.485      -0.202       0.427
34                0.2857      0.168      1.702      0.089      -0.044       0.615
35               -0.1814      0.097     -1.864      0.063      -0.372       0.010
36                0.0165      0.111      0.149      0.882      -0.200       0.233
37               -0.2984      0.102     -2.933      0.003      -0.498      -0.099
38               -0.1799      0.160     -1.125      0.261      -0.494       0.134
39                0.3191      0.220      1.448      0.148      -0.113       0.751
40               -0.3295      0.190     -1.735      0.083      -0.702       0.043
42               -0.4832      0.385     -1.254      0.210      -1.239       0.273
45               -0.6097      0.163     -3.731      0.000      -0.930      -0.289
48               -0.1076      0.195     -0.553      0.580      -0.489       0.274
49               -0.4229      0.360     -1.174      0.240      -1.129       0.284
50                0.1951      0.190      1.027      0.305      -0.178       0.568
51               -0.1719      0.160     -1.077      0.281      -0.485       0.141
52                0.8878      0.225      3.942      0.000       0.446       1.330
53               -0.2831      0.147     -1.921      0.055      -0.572       0.006
54                0.5332      0.209      2.554      0.011       0.124       0.943
56                0.4048      0.175      2.307      0.021       0.061       0.749
57                0.5067      0.268      1.891      0.059      -0.019       1.032
58                0.7756      0.386      2.011      0.045       0.019       1.532
59                0.1241      0.176      0.707      0.480      -0.220       0.468
63               -1.0660      0.428     -2.489      0.013      -1.906      -0.226
70                0.1280      0.276      0.464      0.642      -0.413       0.669
73                0.6469      0.140      4.616      0.000       0.372       0.922
75               -0.4902      0.362     -1.355      0.175      -1.200       0.219
78                0.2387      0.362      0.660      0.509      -0.471       0.948
80               -0.1700      0.388     -0.439      0.661      -0.930       0.590
==============================================================================
Omnibus:                     1037.870   Durbin-Watson:                   0.662
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28809.603
Skew:                           2.954   Prob(JB):                         0.00
Kurtosis:                      23.953   Cond. No.                     4.52e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.07e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
print(np.corrcoef(y, residual))

[[1.         0.01489142]
 [0.01489142 1.        ]]

In [ ]:
#print(np.corrcoef(X, residual))

In [ ]:
print(results.predict())

[0.83126797 0.83413684 0.75668302 ... 2.07336068 2.16990087 2.0455391 ]